# Generated by Django 6.0.2 on 2026-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GermanPrepApp', '0006_germaneesubmission_germaneosubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanCompetencyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('HOREN', 'Hören (Compréhension orale)'), ('LESEN', 'Lesen (Compréhension écrite)'), ('SCHREIBEN', 'Schreiben (Expression écrite)'), ('SPRECHEN', 'Sprechen (Expression orale)'), ('GRAMMATIK', 'Grammatik'), ('WORTSCHATZ', 'Wortschatz')], max_length=20)),
                ('label', models.CharField(help_text='ex: « Trennbare Verben », « Konjunktiv II »', max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tag de compétence (Allemand)',
                'ordering': ['skill', 'label'],
            },
        ),
        migrations.AddField(
            model_name='germanexercise',
            name='competency_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags de compétences testées (ex: Trennbare Verben, Konjunktiv II)', related_name='exercises', to='GermanPrepApp.germancompetencytag'),
        ),
    ]
