# Generated by Django 6.0.2 on 2026-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GermanPrepApp', '0007_germancompetencytag_germanexercise_competency_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='germanresource',
            name='file',
            field=models.FileField(blank=True, help_text='Optionnel. Uploadez un fichier (PDF, MP3, etc.) ou laissez vide si vous utilisez un lien externe.', null=True, upload_to='german_resources/'),
        ),
        migrations.AlterField(
            model_name='germanresource',
            name='url',
            field=models.URLField(blank=True, help_text='Optionnel. Lien vers le PDF / vidéo / ressource (Drive, YouTube, site externe...).', null=True),
        ),
    ]
