# Generated by Django 6.0.2 on 2026-07-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GermanPrepApp', '0008_germanresource_file_alter_germanresource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanPastExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="ex: 'Modellsatz 1' ou 'Sujet Officiel 2025'", max_length=255)),
                ('file', models.FileField(blank=True, help_text="Fichier PDF ou archive du sujet d'examen.", null=True, upload_to='german_past_exams/')),
                ('audio_file', models.FileField(blank=True, help_text='Optionnel. Fichier audio MP3 pour la CO.', null=True, upload_to='german_past_exams/audio/')),
                ('url', models.URLField(blank=True, help_text='Optionnel. Lien externe vers le sujet (ex: site officiel du Goethe-Institut).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(help_text="L'examen associé (ex: Goethe-Zertifikat A1).", on_delete=django.db.models.deletion.CASCADE, related_name='past_exams', to='GermanPrepApp.germanexam')),
            ],
            options={
                'verbose_name': "Annales / Sujet d'Examen",
                'verbose_name_plural': "Annales / Sujets d'Examens",
                'ordering': ['exam', '-created_at'],
            },
        ),
    ]
