# Generated by Django 6.0.2 on 2026-07-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0002_abonnement_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotgaz',
            name='autres_services',
            field=models.TextField(blank=True, help_text="Autres services proposes (vente d'accessoires, tuyaux...)"),
        ),
    ]
