# Generated by Django 5.2.7 on 2025-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('target_role', models.CharField(blank=True, max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('keywords', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('tone', models.CharField(choices=[('pro', 'Pro'), ('convaincant', 'Convaincant'), ('sobre', 'Sobre')], default='pro', max_length=12)),
                ('source', models.CharField(choices=[('form', 'Formulaire'), ('cv', 'Depuis CV')], default='form', max_length=8)),
                ('content', models.TextField()),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
