# Generated by Django 6.0.2 on 2026-07-06 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('germany_opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Ex: Licence en Informatique', max_length=200)),
                ('school', models.CharField(help_text="Nom de l'etablissement", max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Cameroun', max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='CVExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ex: Infirmier diplome d'Etat", max_length=200)),
                ('company', models.CharField(help_text="Nom de l'employeur", max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Cameroun', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Laisser vide si en cours', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Responsabilites principales (3-5 points).')),
                ('order', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CVLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Ex: Deutsch, Francais, Anglais', max_length=50)),
                ('proficiency', models.CharField(choices=[('Muttersprache', 'Langue maternelle'), ('verhandlungssicher', 'Courant (C1/C2)'), ('fliessend', 'Courant (B2)'), ('gute Kenntnisse', 'Bon niveau (B1)'), ('Grundkenntnisse', 'Notions (A1/A2)')], max_length=30)),
                ('certificate', models.CharField(blank=True, help_text='Ex: Goethe-Zertifikat B1, DELF B2', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Langue',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedLebenslauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_offer_title', models.CharField(blank=True, max_length=300)),
                ('custom_offer_company', models.CharField(blank=True, max_length=200)),
                ('content_html', models.TextField(help_text='HTML du Lebenslauf genere')),
                ('content_pdf', models.FileField(blank=True, null=True, upload_to='lebenslauf/pdfs/')),
                ('ai_cover_letter', models.TextField(blank=True, help_text='Lettre de motivation generee par IA (en allemand)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lebenslauf_set', to='germany_opportunities.ausbildungoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lebenslauf_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lebenslauf genere',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GermanCVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, help_text='Adresse actuelle (pays + ville)', max_length=300)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Camerounaise', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Photo professionnelle (obligatoire en Allemagne)', null=True, upload_to='lebenslauf/photos/')),
                ('linkedin', models.URLField(blank=True)),
                ('german_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B1', max_length=5)),
                ('goethe_certified', models.BooleanField(default=False, help_text='Cocher si le certificat Goethe est deja obtenu')),
                ('goethe_cert_date', models.DateField(blank=True, null=True)),
                ('target_sector', models.CharField(blank=True, help_text='Ex: Gesundheit, Informatik, Mechatronik', max_length=100)),
                ('target_cities', models.CharField(blank=True, help_text='Villes acceptees en Allemagne (ex: Berlin, Hamburg, Koeln)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='german_cv_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil CV',
            },
        ),
    ]
