# Generated by Django 6.0.2 on 2026-05-18 09:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('PRESTATAIRE', 'Prestataire'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, related_name='simplo_users', related_query_name='simplo_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='simplo_users', related_query_name='simplo_user', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=80)),
                ('quartier', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
        migrations.CreateModel(
            name='PrestataireProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='simplo/prestataires/')),
                ('ville', models.CharField(max_length=80)),
                ('quartier_base', models.CharField(max_length=120)),
                ('type_service', models.CharField(choices=[('MOTO', 'Moto'), ('LIVRAISON', 'Livraison'), ('COURSES', 'Courses'), ('ENFANTS', 'Récupération enfants')], max_length=20)),
                ('type_vehicule', models.CharField(blank=True, max_length=80)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupé')], default='DISPONIBLE', max_length=20)),
                ('note', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PRESTATAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil prestataire',
                'verbose_name_plural': 'Profils prestataires',
                'indexes': [models.Index(fields=['ville', 'quartier_base', 'type_service', 'statut'], name='simplo_acco_ville_90f454_idx')],
            },
        ),
    ]
