# Generated by Django 6.0.2 on 2026-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplo_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataireprofile',
            name='horaires',
            field=models.CharField(blank=True, default='06h00 - 22h00', max_length=120),
        ),
        migrations.AddField(
            model_name='prestataireprofile',
            name='nombre_courses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prestataireprofile',
            name='zone_couverte',
            field=models.CharField(blank=True, help_text='Quartiers couverts, séparés par des virgules.', max_length=220),
        ),
    ]
