# Generated by Django 5.2.7 on 2025-12-08 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Ex: Menuisier Expert | Comptable Senior', max_length=200, verbose_name='Titre du profil')),
                ('bio', models.TextField(blank=True, verbose_name='À propos')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ville / Localisation')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Lien LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.category', verbose_name='Métier/Catégorie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre du document')),
                ('file', models.FileField(upload_to='portfolio/', verbose_name='Fichier')),
                ('item_type', models.CharField(choices=[('cv', 'CV (PDF)'), ('image', 'Photo de réalisation'), ('ref', 'Lettre de recommandation')], default='image', max_length=10, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.profile')),
            ],
        ),
    ]
