# Generated by Django 5.2.7 on 2026-01-16 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_skill_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='profiles.profile', verbose_name='Profil favori')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Recruteur (utilisateur)')),
            ],
            options={
                'verbose_name': 'Favori recruteur',
                'verbose_name_plural': 'Favoris recruteur',
                'unique_together': {('recruiter', 'profile')},
            },
        ),
    ]
