# Generated by Django 5.2.7 on 2025-10-21 09:53

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscriptionplan_remove_accesscode_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcode',
            name='expiration_date',
            field=models.DateTimeField(default=billing.models.default_expiration_date),
        ),
    ]
