# Generated by Django 6.0.2 on 2026-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
