# Generated by Django 6.0.2 on 2026-06-23 20:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_affiliateprofile_click_count'),
        ('business', '0017_unmetsearchrequest_ai_category_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('buyer_name', models.CharField(max_length=120, verbose_name="Nom de l'acheteur")),
                ('buyer_phone', models.CharField(max_length=30, verbose_name='Téléphone WhatsApp')),
                ('buyer_address', models.CharField(max_length=255, verbose_name='Adresse de livraison')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total (FCFA)')),
                ('reseller_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission revendeur (FCFA)')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Frais de service (FCFA)')),
                ('delivery_code', models.CharField(db_index=True, max_length=10, verbose_name='Code secret de validation')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de livraison'), ('DELIVERED', 'Livrée'), ('CANCELED', 'Annulée')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_orders', to='business.businessprofile')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resold_orders', to='billing.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Commande de revente',
                'verbose_name_plural': 'Commandes de revente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solde (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Portefeuille prestataire',
                'verbose_name_plural': 'Portefeuilles prestataires',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix de vente (FCFA)')),
                ('reseller_commission', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission revendeur (FCFA)')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de service plateforme (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Config affiliation produit',
                'verbose_name_plural': 'Configs affiliation produit',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='billing_aff_content_acd765_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResellerProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('promo_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resold_products', to='billing.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Lien de revente produit',
                'verbose_name_plural': 'Liens de revente produit',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='billing_res_content_667081_idx')],
            },
        ),
    ]
