# Generated by Django 6.0.2 on 2026-05-30 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('contenu_preview', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
                'ordering': ['nom', 'langue'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('message_template', models.TextField(help_text='Message a envoyer. Utilise {{prenom}} pour personnaliser.')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee')], default='brouillon', max_length=20)),
                ('filtre_role', models.CharField(blank=True, help_text='ex: vendeur, acheteur, tous', max_length=50)),
                ('filtre_ville', models.CharField(blank=True, max_length=100)),
                ('filtre_date_inscription_depuis', models.DateField(blank=True, null=True)),
                ('total_destinataires', models.IntegerField(default=0)),
                ('total_envoyes', models.IntegerField(default=0)),
                ('total_livres', models.IntegerField(default=0)),
                ('total_lus', models.IntegerField(default=0)),
                ('total_echecs', models.IntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('lance_le', models.DateTimeField(blank=True, null=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne WhatsApp',
                'verbose_name_plural': 'Campagnes WhatsApp',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MessageEnvoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(max_length=20)),
                ('message_final', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoye'), ('livre', 'Livre'), ('lu', 'Lu'), ('echec', 'Echec')], default='en_attente', max_length=20)),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('erreur', models.TextField(blank=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_agent.campagne')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message WhatsApp envoye',
                'verbose_name_plural': 'Messages WhatsApp envoyes',
                'ordering': ['-mis_a_jour_le'],
            },
        ),
    ]
