# Generated by Django 6.0.2 on 2026-05-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validee'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee')], default='brouillon', max_length=20),
        ),
    ]
