# Generated by Django 6.0.2 on 2026-05-30 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_agent', '0001_initial'),
        ('whatsapp_agent', '0002_alter_campagne_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageenvoi',
            name='commercial_prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_whatsapp', to='commercial_agent.prospectbusiness'),
        ),
        migrations.AddField(
            model_name='messageenvoi',
            name='destinataire_nom',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='messageenvoi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
