# Generated by Django 6.0.2 on 2026-05-30 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0003_messageenvoi_commercial_prospect_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=180)),
                ('numero', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('groupe', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('manuel', 'Manuel'), ('api', 'API')], default='api', max_length=20)),
                ('consentement_confirme', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('importe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact WhatsApp autorise',
                'verbose_name_plural': 'Contacts WhatsApp autorises',
                'ordering': ['-cree_le'],
            },
        ),
    ]
