# Generated by Django 6.0.2 on 2026-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0004_contactwhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='destinataires_contacts',
            field=models.ManyToManyField(blank=True, help_text='Contacts WhatsApp selectionnes manuellement pour cette campagne.', related_name='campagnes_whatsapp', to='whatsapp_agent.contactwhatsapp'),
        ),
    ]
