# Generated by Django 6.0.2 on 2026-09-17 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_agent', '0003_prospectbusiness_whatsapp_verification_and_more'),
        ('whatsapp_agent', '0007_outreachlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('interesse', '🔥 Intéressé'), ('qualifie', '⭐ Qualifié'), ('converti', '✅ Converti / Vendu'), ('ferme', 'Archivé / Fermé')], db_index=True, default='nouveau', max_length=20)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], db_index=True, default='normale', max_length=20)),
                ('dernier_message_apercu', models.TextField(blank=True)),
                ('dernier_message_le', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('non_lus_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation WhatsApp',
                'verbose_name_plural': 'Conversations WhatsApp',
                'ordering': ['-dernier_message_le', '-mis_a_jour_le'],
            },
        ),
        migrations.CreateModel(
            name='MessageWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('entrant', 'Entrant (Prospect)'), ('sortant', 'Sortant (E-Shelle)')], db_index=True, default='entrant', max_length=10)),
                ('texte', models.TextField(blank=True)),
                ('whatsapp_msg_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoye'), ('livre', 'Livre'), ('lu', 'Lu'), ('recu', 'Recu'), ('echec', 'Echec')], default='recu', max_length=20)),
                ('media_type', models.CharField(blank=True, max_length=30)),
                ('media_url', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Message WhatsApp (Chat)',
                'verbose_name_plural': 'Messages WhatsApp (Chats)',
                'ordering': ['cree_le'],
            },
        ),
        migrations.RenameIndex(
            model_name='outreachlog',
            new_name='whatsapp_ag_canal_87631c_idx',
            old_name='whatsapp_ag_canal_6f0e33_idx',
        ),
        migrations.AddField(
            model_name='conversationwhatsapp',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_whatsapp_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationwhatsapp',
            name='commercial_prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_whatsapp', to='commercial_agent.prospectbusiness'),
        ),
        migrations.AddField(
            model_name='conversationwhatsapp',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp_agent.contactwhatsapp'),
        ),
        migrations.AddField(
            model_name='conversationwhatsapp',
            name='derniere_campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_initiees', to='whatsapp_agent.campagne'),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_inbox', to='whatsapp_agent.campagne'),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_agent.conversationwhatsapp'),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='envoye_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_whatsapp_envoyes', to=settings.AUTH_USER_MODEL),
        ),
    ]
