# Generated by Django 6.0.2 on 2026-09-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0008_conversationwhatsapp_messagewhatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTestSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('erreur', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_envoi', to='whatsapp_agent.campagne')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
