# Generated by Django 6.0.2 on 2026-10-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0009_whatsapp_test_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagewhatsapp',
            name='erreur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='media_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='media_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='media_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagewhatsapp',
            name='meta_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagewhatsapp',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoye'), ('livre', 'Livre'), ('lu', 'Lu'), ('recu', 'Recu'), ('simulation', 'Simulation'), ('echec', 'Echec')], default='recu', max_length=20),
        ),
    ]
