# Generated by Django 6.0.2 on 2026-05-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='offrejob',
            new_name='jobs_offrej_is_acti_1dd413_idx',
            old_name='jobs_offrej_is_acti_d90815_idx',
        ),
        migrations.RenameIndex(
            model_name='offrejob',
            new_name='jobs_offrej_ville_i_6a2d6d_idx',
            old_name='jobs_offrej_ville_i_5c1093_idx',
        ),
    ]
