# Generated by Django 6.0.2 on 2026-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_offrej_is_acti_d90815_idx_jobs_offrej_is_acti_1dd413_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaJobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_nr', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('lmia_status', models.CharField(default='Non précisé', help_text='EIMT approuvé, EIMT en cours, exempté ou non précisé', max_length=50)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url_apply', models.URLField(max_length=500)),
                ('ai_summary_fr', models.TextField(blank=True, help_text="Résumé de l'offre par l'IA")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offre Canada',
                'verbose_name_plural': 'Offres Canada',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
