# Generated by Django 6.0.2 on 2026-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_canadajoboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_nr', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('provider', models.CharField(help_text='Organisme ou Université émettrice', max_length=200)),
                ('amount', models.CharField(blank=True, help_text='Valeur de la bourse', max_length=100)),
                ('eligibility', models.TextField(blank=True, help_text="Critères d'éligibilité")),
                ('deadline', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url_apply', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bourse Canada',
                'verbose_name_plural': 'Bourses Canada',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
