# Generated by Django 6.0.2 on 2026-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_canadascholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaVisitorOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_nr', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=350)),
                ('organizer', models.CharField(help_text='Organisme ou Association hôte', max_length=250)),
                ('event_date', models.CharField(blank=True, help_text="Date de déroulement de l'événement", max_length=150)),
                ('location', models.CharField(help_text='Ville et province au Canada', max_length=200)),
                ('deadline', models.CharField(blank=True, help_text="Date limite d'inscription", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url_apply', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opportunité Visa Visiteur',
                'verbose_name_plural': 'Opportunités Visa Visiteur',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
