# Generated by Django 6.0.2 on 2026-07-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_canadavisitoropportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='canadajoboffer',
            name='deadline',
            field=models.CharField(blank=True, help_text='Date limite pour postuler, si connue', max_length=100),
        ),
    ]
