# Generated by Django 6.0.2 on 2026-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_canadajoboffer_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_nr', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=350)),
                ('category', models.CharField(help_text="Ex: Tirage, Loi d'immigration, Opportunité, Communiqué", max_length=100)),
                ('published_date', models.CharField(blank=True, help_text="Date de publication de l'information", max_length=100)),
                ('summary', models.TextField(help_text="Résumé détaillé de l'actualité en français")),
                ('url_source', models.URLField(help_text='Lien officiel source vérifié (Canada.ca / IRCC)', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité Canada',
                'verbose_name_plural': 'Actualités Canada',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
