# Generated by Django 6.0.2 on 2026-09-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_canadanews'),
    ]

    operations = [
        migrations.AddField(
            model_name='canadajoboffer',
            name='source_posted_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date de publication sur le site source', null=True),
        ),
    ]
