# Generated by Django 6.0.2 on 2026-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ecole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingschool',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
