# Generated by Django 6.0.2 on 2026-09-02 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ecole', '0002_drivingschool_latitude_drivingschool_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingschool',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='auto_ecole/logos/'),
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_schools', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='price_note',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='drivingschool',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
