# Generated by Django 6.0.2 on 2026-05-27 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shelle_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralAgentQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('query', models.TextField()),
                ('module', models.CharField(db_index=True, max_length=40)),
                ('response', models.TextField(blank=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('premium_results_count', models.PositiveIntegerField(default=0)),
                ('had_results', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='central_agent_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche Agent Central',
                'verbose_name_plural': 'Recherches Agent Central',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='e_shelle_ai_module_342e64_idx'), models.Index(fields=['had_results', 'created_at'], name='e_shelle_ai_had_res_59ca69_idx')],
            },
        ),
    ]
