# Generated by Django 6.0.2 on 2026-06-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shelle_ai', '0002_centralagentquerylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image générée'), ('video', 'Vidéo générée'), ('mixed', 'Texte + Image')], default='text', max_length=10),
        ),
    ]
