# Generated by Django 6.0.2 on 2026-10-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boutique_product_id', models.IntegerField(db_index=True)),
                ('visitor_session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('visitor_phone', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('converted', models.BooleanField(db_index=True, default=False)),
                ('abandoned_sent', models.BooleanField(db_index=True, default=False)),
                ('whatsapp_opt_in', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['converted', 'abandoned_sent', 'viewed_at'], name='whatsapp_co_convert_7addaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductWhatsAppSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boutique_product_id', models.IntegerField(db_index=True)),
                ('waba_id', models.CharField(db_index=True, max_length=64)),
                ('whatsapp_product_id', models.CharField(blank=True, max_length=128)),
                ('sync_status', models.CharField(db_index=True, default='pending', max_length=24)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_synced_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('boutique_product_id', 'waba_id'), name='wa_commerce_product_waba_uniq')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boutique_id', models.IntegerField(db_index=True)),
                ('waba_id', models.CharField(max_length=64)),
                ('phone_number_id', models.CharField(max_length=64)),
                ('catalog_id', models.CharField(blank=True, max_length=64)),
                ('display_phone_number', models.CharField(blank=True, max_length=32)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['boutique_id'],
                'constraints': [models.UniqueConstraint(fields=('boutique_id',), name='wa_commerce_boutique_config_uniq')],
            },
        ),
    ]
