# Generated by Django 6.0.2 on 2026-10-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_alter_businesscatalogitem_video_url'),
        ('whatsapp_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(max_length=64, unique=True)),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('meta_business_id', models.CharField(blank=True, max_length=64)),
                ('catalog_id', models.CharField(blank=True, max_length=64)),
                ('display_phone_number', models.CharField(blank=True, max_length=32)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('phone_registered', models.BooleanField(default=False)),
                ('webhook_subscribed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('connecting', 'Connexion en cours'), ('active', 'Connecte'), ('action_required', 'Action requise'), ('disconnected', 'Deconnecte')], default='connecting', max_length=24)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connection', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Connexion WhatsApp Business',
                'verbose_name_plural': 'Connexions WhatsApp Business',
                'ordering': ['business_id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessWhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=180)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('consent_source', models.CharField(blank=True, max_length=120)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Contact WhatsApp business',
                'verbose_name_plural': 'Contacts WhatsApp business',
                'ordering': ['-last_activity_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BusinessWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=200, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Entrant'), ('outbound', 'Sortant')], max_length=12)),
                ('message_type', models.CharField(default='text', max_length=32)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=24)),
                ('meta_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_commerce.businesswhatsappcontact')),
            ],
            options={
                'verbose_name': 'Message WhatsApp business',
                'verbose_name_plural': 'Messages WhatsApp business',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='businesswhatsappcontact',
            index=models.Index(fields=['business', 'last_activity_at'], name='whatsapp_co_busines_2eb0de_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesswhatsappcontact',
            constraint=models.UniqueConstraint(fields=('business', 'phone'), name='wa_biz_contact_phone_uniq'),
        ),
    ]
