# Generated by Django 6.0.2 on 2026-10-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_alter_businesscatalogitem_video_url'),
        ('whatsapp_commerce', '0002_businesswhatsappconnection_businesswhatsappcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCatalogWhatsAppSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_id', models.CharField(max_length=128)),
                ('whatsapp_product_id', models.CharField(blank=True, max_length=128)),
                ('sync_status', models.CharField(choices=[('pending', 'En attente'), ('synced', 'Synchronisé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], db_index=True, default='pending', max_length=24)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_synced_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='businesswhatsappcontact',
            name='next_follow_up_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='businesswhatsappcontact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesswhatsappcontact',
            name='pipeline_status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('open', 'À traiter'), ('qualified', 'Qualifié'), ('won', 'Gagné'), ('lost', 'Perdu')], db_index=True, default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='businesswhatsappcontact',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='businesswhatsappcontact',
            index=models.Index(fields=['business', 'pipeline_status', 'next_follow_up_at'], name='whatsapp_co_busines_a63022_idx'),
        ),
        migrations.AddField(
            model_name='businesscatalogwhatsappsync',
            name='business_catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_syncs', to='business.businesscatalogitem'),
        ),
        migrations.AddField(
            model_name='businesscatalogwhatsappsync',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_syncs', to='whatsapp_commerce.businesswhatsappconnection'),
        ),
        migrations.AddIndex(
            model_name='businesscatalogwhatsappsync',
            index=models.Index(fields=['connection', 'sync_status'], name='whatsapp_co_connect_a2fe0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesscatalogwhatsappsync',
            constraint=models.UniqueConstraint(fields=('business_catalog_item', 'connection'), name='wa_biz_item_conn_sync_uniq'),
        ),
    ]
