# Generated by Django 6.0.2 on 2026-10-07 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_commerce', '0003_businesscatalogwhatsappsync_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswhatsappcontact',
            name='consent_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_whatsapp_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScheduledBusinessWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=128)),
                ('template_language', models.CharField(max_length=32)),
                ('body_parameters', models.JSONField(blank=True, default=list)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('sending', 'En cours'), ('sent', 'Accepté par Meta'), ('failed', 'Échec'), ('cancelled', 'Annulé')], db_index=True, default='scheduled', max_length=16)),
                ('wa_message_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('delivery_status', models.CharField(blank=True, max_length=24)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='whatsapp_commerce.businesswhatsappconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='whatsapp_commerce.businesswhatsappcontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_business_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for', 'pk'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='whatsapp_co_status_47c962_idx')],
            },
        ),
    ]
