# Generated by Django 6.0.2 on 2026-06-03 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrackJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('prompt', models.TextField()),
                ('mood', models.CharField(choices=[('afrobeat', 'Afrobeat dynamique'), ('corporate', 'Corporate positif'), ('emotional', 'Emotionnel / storytelling'), ('ambient', 'Ambiance douce'), ('energetic', 'Promo energique')], default='afrobeat', max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Termine'), ('failed', 'Echec')], default='pending', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_studio/music/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_track_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musique video',
                'verbose_name_plural': 'Musiques video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sample', models.FileField(upload_to='audio_studio/voice_samples/')),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('consent_note', models.CharField(blank=True, max_length=240)),
                ('provider_voice_id', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil voix',
                'verbose_name_plural': 'Profils voix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceOverJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('script', models.TextField()),
                ('mode', models.CharField(choices=[('local', 'Test local'), ('clone', 'Voix clonee')], default='local', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Termine'), ('failed', 'Echec')], default='pending', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_studio/voiceovers/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceover_jobs', to=settings.AUTH_USER_MODEL)),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='audio_studio.voiceprofile')),
            ],
            options={
                'verbose_name': 'Voix-off',
                'verbose_name_plural': 'Voix-off',
                'ordering': ['-created_at'],
            },
        ),
    ]
