# Generated by Django 6.0.2 on 2026-09-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceoverjob',
            name='openai_voice',
            field=models.CharField(choices=[('alloy', 'Alloy - neutre'), ('echo', 'Echo - grave, masculin'), ('fable', 'Fable - chaleureux'), ('onyx', 'Onyx - profond, masculin'), ('nova', 'Nova - dynamique, feminin'), ('shimmer', 'Shimmer - doux, feminin')], default='nova', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiceoverjob',
            name='mode',
            field=models.CharField(choices=[('local', 'Voix IA (OpenAI)'), ('clone', 'Ma voix clonee (bientot disponible)')], default='local', max_length=20),
        ),
    ]
