# Generated by Django 6.0.2 on 2026-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0002_voiceoverjob_openai_voice_alter_voiceoverjob_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceoverjob',
            name='mode',
            field=models.CharField(choices=[('local', 'Voix IA (OpenAI)'), ('clone', 'Ma voix clonee')], default='local', max_length=20),
        ),
    ]
