# Generated by Django 5.2.7 on 2026-04-20 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone / WhatsApp')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Pays de résidence actuel')),
                ('consultation_type', models.CharField(choices=[('visa_etude', 'Visa Etudes'), ('visa_travail', 'Visa Travail'), ('residence_permanente', 'Résidence Permanente'), ('langue', 'Préparation Test de Langue (TCF/TEF/DELF/DALF)'), ('allemand', "Cours d'Allemand"), ('cv', 'Création / Optimisation CV'), ('profil', 'Profil Candidat & Mise en Relation'), ('job_search', "Recherche d'Emploi à l'International"), ('autre', 'Autre / Non listé')], max_length=30, verbose_name='Type de consultation')),
                ('destination_country', models.CharField(blank=True, max_length=80, verbose_name='Pays de destination visé')),
                ('message', models.TextField(verbose_name='Décrivez votre situation et vos besoins')),
                ('budget', models.CharField(choices=[('less_50', 'Moins de 50 €'), ('50_100', '50 – 100 €'), ('100_200', '100 – 200 €'), ('200_plus', '200 € et plus'), ('to_discuss', 'À discuter')], default='to_discuss', max_length=20, verbose_name='Budget indicatif')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Date de consultation souhaitée')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contacté(e)'), ('in_progress', 'En cours de traitement'), ('completed', 'Traité(e)'), ('cancelled', 'Annulé(e)')], db_index=True, default='new', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes internes (admin uniquement)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de consultation',
                'verbose_name_plural': 'Demandes de consultation',
                'ordering': ['-created_at'],
            },
        ),
    ]
