# Generated by Django 5.2.7 on 2026-01-27 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Protocole de protection Immigration97', max_length=255)),
                ('content', models.TextField(help_text='Texte juridique officiel du protocole')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Protocole de protection',
                'verbose_name_plural': 'Protocoles de protection',
            },
        ),
    ]
