# Generated by Django 6.0.2 on 2026-05-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0008_alter_businessprofile_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('appel', 'Appel'), ('facebook', 'Facebook'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('module', models.CharField(blank=True, max_length=40)),
                ('contenu', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Script commercial',
                'verbose_name_plural': 'Scripts commerciaux',
                'ordering': ['canal', 'module', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProspectBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                ('module', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('business_profile', 'Fiche business'), ('user', 'Utilisateur'), ('import', 'Import'), ('demo', 'Demo')], default='manuel', max_length=30)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('qualifie', 'Qualifie'), ('contacte', 'Contacte'), ('interesse', 'Interesse'), ('negociation', 'Negociation'), ('paye', 'Paye'), ('perdu', 'Perdu'), ('a_relancer', 'A relancer')], db_index=True, default='nouveau', max_length=30)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], db_index=True, default='normale', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('montant_potentiel_xaf', models.PositiveIntegerField(default=0)),
                ('plan_recommande', models.CharField(blank=True, max_length=40)),
                ('prochain_contact', models.DateField(blank=True, null=True)),
                ('dernier_contact', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_commerciaux', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_prospects', to='business.businessprofile')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospect business',
                'verbose_name_plural': 'Prospects business',
                'ordering': ['-score', 'prochain_contact', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CampagneProspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                ('objectif', models.TextField(blank=True)),
                ('module_cible', models.CharField(blank=True, max_length=40)),
                ('ville_cible', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('active', 'Active'), ('terminee', 'Terminee'), ('pause', 'Pause')], default='brouillon', max_length=20)),
                ('message_base', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('lance_le', models.DateTimeField(blank=True, null=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospects', models.ManyToManyField(blank=True, related_name='campagnes_prospection', to='commercial_agent.prospectbusiness')),
            ],
            options={
                'verbose_name': 'Campagne de prospection',
                'verbose_name_plural': 'Campagnes de prospection',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='RelanceProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('appel', 'Appel'), ('visite', 'Visite terrain'), ('note', 'Note'), ('paiement', 'Paiement')], default='whatsapp', max_length=20)),
                ('resultat', models.CharField(choices=[('a_faire', 'A faire'), ('envoye', 'Envoye'), ('reponse', 'Reponse recue'), ('interesse', 'Interesse'), ('refus', 'Refus'), ('paye', 'Paye')], default='a_faire', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('montant_xaf', models.PositiveIntegerField(default=0)),
                ('prochaine_relance', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances', to='commercial_agent.campagneprospection')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='commercial_agent.prospectbusiness')),
            ],
            options={
                'verbose_name': 'Relance prospect',
                'verbose_name_plural': 'Relances prospects',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='prospectbusiness',
            index=models.Index(fields=['statut', 'priorite'], name='commercial__statut_dc3498_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectbusiness',
            index=models.Index(fields=['module', 'ville'], name='commercial__module_25d304_idx'),
        ),
    ]
