# Generated by Django 6.0.2 on 2026-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectbusiness',
            name='source',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('business_profile', 'Fiche business'), ('user', 'Utilisateur'), ('import', 'Import'), ('sourcing_web', 'Sourcing Web'), ('facebook', 'Facebook'), ('demo', 'Demo')], default='manuel', max_length=30),
        ),
    ]
