# Generated by Django 6.0.2 on 2026-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_agent', '0002_alter_prospectbusiness_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectbusiness',
            name='whatsapp_verification',
            field=models.CharField(choices=[('unknown', 'À vérifier'), ('confirmed', 'Présent sur WhatsApp'), ('absent', 'Absent de WhatsApp')], db_index=True, default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='prospectbusiness',
            name='whatsapp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectbusiness',
            name='whatsapp_verified_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
