# Generated by Django 6.0.2 on 2026-07-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germany_opportunities', '0002_useropportunitybookmark_user_and_unique_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ausbildungoffer',
            new_name='germany_opp_is_acti_a41f9e_idx',
            old_name='germany_opp_is_acti_idx1',
        ),
        migrations.RenameIndex(
            model_name='ausbildungoffer',
            new_name='germany_opp_is_acti_6cd8fd_idx',
            old_name='germany_opp_is_acti_idx2',
        ),
        migrations.AlterField(
            model_name='scholarshipopportunity',
            name='countries',
            field=models.CharField(blank=True, help_text="Ex: Cameroun, Senegal, Cote d'Ivoire", max_length=500),
        ),
    ]
