# Generated by Django 6.0.2 on 2026-07-24 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germany_opportunities', '0003_rename_germany_opp_is_acti_idx1_germany_opp_is_acti_a41f9e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AusbildungInterviewSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('messages', models.JSONField(default=list, help_text='Historique de chat [{"role": "...", "content": "..."}]')),
                ('score', models.IntegerField(blank=True, help_text='Note finale (0-100)', null=True)),
                ('feedback', models.TextField(blank=True, help_text="Rapport d'évaluation de l'IA en français")),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausbildung_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation Entretien',
                'verbose_name_plural': 'Simulations Entretiens',
                'ordering': ['-created_at'],
            },
        ),
    ]
