# Generated by Django 6.0.2 on 2026-09-09 11:39

from django.db import migrations, models


def bump_b1_to_b2(apps, schema_editor):
    AusbildungOffer = apps.get_model('germany_opportunities', 'AusbildungOffer')
    AusbildungOffer.objects.filter(language_req='B1').update(language_req='B2')


def revert_b2_to_b1(apps, schema_editor):
    AusbildungOffer = apps.get_model('germany_opportunities', 'AusbildungOffer')
    AusbildungOffer.objects.filter(language_req='B2').update(language_req='B1')


class Migration(migrations.Migration):

    dependencies = [
        ('germany_opportunities', '0004_ausbildunginterviewsimulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausbildungoffer',
            name='language_req',
            field=models.CharField(choices=[('B1', 'B1 (intermediaire)'), ('B2', 'B2 (intermediaire superieur)'), ('C1', 'C1 (avance)'), ('A2', 'A2 (elementaire)')], default='B2', max_length=5),
        ),
        migrations.RunPython(bump_b1_to_b2, revert_b2_to_b1),
    ]
