# Generated by Django 5.2.7 on 2026-01-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('titre_poste', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('resume_professionnel', models.TextField(blank=True, help_text='2-3 phrases décrivant votre profil', verbose_name='Résumé professionnel (FR)')),
                ('summary', models.TextField(blank=True, help_text='Professional summary', verbose_name='Résumé (EN)')),
                ('is_published', models.BooleanField(default=False, help_text='CV visible publiquement', verbose_name='CV publié')),
                ('pays_cible', models.CharField(blank=True, help_text='Pays où vous souhaitez postuler', max_length=100, verbose_name='Pays cible')),
                ('language', models.CharField(blank=True, help_text='Langue du CV (FR/EN)', max_length=50, verbose_name='Langue principale')),
                ('profession', models.CharField(blank=True, help_text='Domaine professionnel principal', max_length=200, verbose_name='Profession/Secteur')),
                ('current_step', models.IntegerField(default=1, help_text='Étape en cours du wizard (1, 2, 3)', verbose_name='Étape actuelle')),
                ('is_completed', models.BooleanField(default=False, help_text='Toutes les étapes sont terminées', verbose_name='CV complété')),
                ('step1_completed', models.BooleanField(default=False, verbose_name='Étape 1 complétée')),
                ('step2_completed', models.BooleanField(default=False, verbose_name='Étape 2 complétée')),
                ('step3_completed', models.BooleanField(default=False, verbose_name='Étape 3 complétée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_generator.cvtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Compétence')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('organisme', models.CharField(blank=True, max_length=200, verbose_name='Organisme')),
                ('annee', models.CharField(blank=True, max_length=10, verbose_name='Année')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('credential_url', models.URLField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-annee', '-date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cv_uploads/')),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='cv_generator.cv')),
            ],
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='Snapshot complet du CV à un instant T')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cv_generator.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=200, verbose_name='Poste')),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('date_debut', models.CharField(blank=True, max_length=20, verbose_name='Date de début')),
                ('date_fin', models.CharField(blank=True, max_length=20, null=True, verbose_name='Date de fin')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_raw', models.TextField(blank=True)),
                ('description_ai', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-date_debut', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(blank=True, max_length=200, verbose_name='Diplôme')),
                ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('annee_obtention', models.CharField(blank=True, max_length=50, verbose_name='Année')),
                ('diploma', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-annee_obtention', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='cv_generator.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(blank=True, max_length=50, verbose_name='Langue')),
                ('niveau', models.CharField(blank=True, choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Courant', 'Courant'), ('Bilingue', 'Bilingue'), ('Langue maternelle', 'Langue maternelle')], max_length=50, verbose_name='Niveau')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langues', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv_generator.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Technique'), ('soft', 'Soft Skill'), ('lang', 'Langue'), ('other', 'Autre')], default='tech', max_length=20)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_generator.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='cv_generator.cv')),
            ],
        ),
    ]
