# Generated by Django 5.2.7 on 2025-12-11 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('description', models.TextField(verbose_name='Description')),
                ('industry', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('country', models.CharField(max_length=50, verbose_name='Pays')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='Score de popularité')),
                ('html_template', models.TextField(verbose_name='Template HTML')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cv_templates/', verbose_name='Aperçu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('style_type', models.CharField(choices=[('professional', 'Professionnel'), ('creative', 'Créatif'), ('traditional', 'Traditionnel'), ('modern', 'Moderne'), ('canadian', 'Canadien'), ('european', 'Européen'), ('american', 'Américain')], default='professional', max_length=50, verbose_name='Type de style')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Modèle de CV',
                'verbose_name_plural': 'Modèles de CV',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession/Titre du poste')),
                ('pays_cible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays ciblé')),
                ('current_step', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Étape actuelle')),
                ('step1_completed', models.BooleanField(default=False, verbose_name='Étape 1 complétée')),
                ('step2_completed', models.BooleanField(default=False, verbose_name='Étape 2 complétée')),
                ('step3_completed', models.BooleanField(default=False, verbose_name='Étape 3 complétée')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structure: {personal_info, experiences, education, skills, languages, summary, etc.}', verbose_name='Données du CV')),
                ('is_completed', models.BooleanField(default=False, verbose_name='CV complété')),
                ('is_published', models.BooleanField(default=False, verbose_name='CV publié')),
                ('last_analysis', models.JSONField(blank=True, null=True, verbose_name='Dernière analyse IA')),
                ('quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de qualité')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé professionnel')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière modification')),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_generator.cvtemplate', verbose_name='Modèle de CV')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la certification')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisme')),
                ('date_obtained', models.DateField(verbose_name="Date d'obtention")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID de certification')),
                ('credential_url', models.URLField(blank=True, verbose_name='URL de vérification')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='CVExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name="Format d'export")),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'export")),
                ('file_size', models.IntegerField(blank=True, help_text='Taille en bytes', null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': "Historique d'export",
                'verbose_name_plural': 'Historique des exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.CharField(max_length=150, verbose_name='Diplôme')),
                ('institution', models.CharField(max_length=150, verbose_name='Institution')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé du poste')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu')),
                ('description_raw', models.TextField(verbose_name='Description brute')),
                ('description_optimised', models.TextField(blank=True, verbose_name='Description optimisée IA')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Expérience professionnelle',
                'verbose_name_plural': 'Expériences professionnelles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du loisir')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': "Centre d'intérêt",
                'verbose_name_plural': "Centres d'intérêt",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Langue')),
                ('level', models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Intermédiaire avancé'), ('C1', 'C1 - Avancé'), ('C2', 'C2 - Maîtrise'), ('natif', 'Langue maternelle')], max_length=20, verbose_name='Niveau')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('url', models.URLField(blank=True, verbose_name='URL du projet')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Technologies utilisées')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=50, verbose_name='Niveau')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('technique', 'Compétence Technique'), ('soft', 'Compétence Interpersonnelle'), ('outil', 'Outil / Logiciel')], db_index=True, max_length=50)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation')),
                ('role', models.CharField(max_length=200, verbose_name='Rôle')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Expérience bénévole',
                'verbose_name_plural': 'Expériences bénévoles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['utilisateur', '-date_modification'], name='cv_generato_utilisa_50a20c_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['is_completed', 'is_published'], name='cv_generato_is_comp_c2d13f_idx'),
        ),
    ]
