# Generated by Django 5.2.7 on 2026-01-10 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['id'], 'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.AddField(
            model_name='competence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competence',
            name='niveau',
            field=models.CharField(blank=True, help_text='Ex: Débutant, Intermédiaire, Avancé, Expert', max_length=50, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom de la compétence'),
        ),
    ]
