# Generated by Django 5.2.7 on 2026-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2),
        ),
    ]
