# Generated by Django 5.2.7 on 2025-10-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('popularity_score', models.IntegerField(default=0)),
                ('html_template', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cv_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.RemoveField(
            model_name='cv',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='ai_review',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='content',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='country_target',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.AddField(
            model_name='cv',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données du CV'),
        ),
        migrations.AddField(
            model_name='cv',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='cv',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='CV complété'),
        ),
        migrations.AddField(
            model_name='cv',
            name='pays_cible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays ciblé'),
        ),
        migrations.AddField(
            model_name='cv',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_generator.cvtemplate', verbose_name='Modèle de CV'),
        ),
    ]
