# Generated by Django 5.2.7 on 2026-01-12 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0002_alter_competence_options_competence_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvtemplate',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Template de CV', 'verbose_name_plural': 'Templates de CV'},
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='style',
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='order',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage (0 = premier)"),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='template_file',
            field=models.CharField(default='cv_canada_ats.html', help_text='Nom du fichier template (ex: cv_canada_ats.html)', max_length=200),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du template'),
        ),
    ]
