# Generated by Django 5.2.7 on 2025-11-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0003_cvexporthistory_alter_cv_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='cv_generator.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé du poste')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description des tâches et réalisations')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Expérience professionnelle',
                'verbose_name_plural': 'Expériences professionnelles',
                'ordering': ['-start_date'],
            },
        ),
    ]
