# Generated by Django 5.2.7 on 2026-01-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0003_cvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description_ai',
            field=models.TextField(blank=True),
        ),
    ]
