# Generated by Django 5.2.7 on 2026-01-13 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0003_alter_cvtemplate_options_remove_cvtemplate_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-date_obtained', '-created_at'], 'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['created_at'], 'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.AlterModelOptions(
            name='cvversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Expérience', 'verbose_name_plural': 'Expériences'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-end_date', '-created_at'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='langue',
            options={'ordering': ['created_at'], 'verbose_name': 'Langue', 'verbose_name_plural': 'Langues'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-start_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='organisme',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='langue',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='niveau',
        ),
        migrations.AddField(
            model_name='certification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='style',
            field=models.CharField(default='canada_ats', help_text='Identifiant de style (ex: canada_ats, modern, classic)', max_length=60),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobby',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='langue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='annee',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Année (fallback)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='niveau',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Étape actuelle'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='CV complété'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='CV publié'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='language',
            field=models.CharField(blank=True, default='fr', max_length=10, verbose_name='Langue principale'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='pays_cible',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pays cible'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Profession/Secteur'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='resume_professionnel',
            field=models.TextField(blank=True, default='', help_text='2-3 phrases décrivant votre profil', verbose_name='Résumé professionnel (FR)'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Professional summary', verbose_name='Résumé (EN)'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='cv_generator.cvtemplate', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='titre_poste',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Titre du poste'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_ai',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Titre/Poste'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='annee_obtention',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Année (fallback)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='formation',
            name='diploma',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='langue',
            name='level',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['cv', '-date_obtained'], name='cv_generato_cv_id_77a62a_idx'),
        ),
        migrations.AddIndex(
            model_name='competence',
            index=models.Index(fields=['cv', 'created_at'], name='cv_generato_cv_id_c9ccf2_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['user', '-updated_at'], name='cv_generato_user_id_5cfa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['is_completed', 'is_published'], name='cv_generato_is_comp_c2d13f_idx'),
        ),
        migrations.AddIndex(
            model_name='cvtemplate',
            index=models.Index(fields=['is_active', 'is_premium', 'order'], name='cv_generato_is_acti_53de55_idx'),
        ),
        migrations.AddIndex(
            model_name='cvversion',
            index=models.Index(fields=['cv', '-created_at'], name='cv_generato_cv_id_1e74cb_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['cv', '-start_date'], name='cv_generato_cv_id_4f1073_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['cv', '-end_date'], name='cv_generato_cv_id_8eaed3_idx'),
        ),
        migrations.AddIndex(
            model_name='hobby',
            index=models.Index(fields=['cv', 'created_at'], name='cv_generato_cv_id_bc8f20_idx'),
        ),
        migrations.AddIndex(
            model_name='langue',
            index=models.Index(fields=['cv', 'created_at'], name='cv_generato_cv_id_5dbf46_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['cv', '-start_date'], name='cv_generato_cv_id_eab87d_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['cv', 'category'], name='cv_generato_cv_id_41a3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['cv', '-start_date'], name='cv_generato_cv_id_7518cf_idx'),
        ),
    ]
