# Generated by Django 5.2.7 on 2026-01-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0004_experience_description_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtemplate',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Template réservé aux comptes Premium'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='style',
            field=models.CharField(help_text='Identifiant technique du template (ex: canada, europe, modern)', max_length=50),
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='cv_generator.cv'),
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='Snapshot complet du CV à un instant T')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cv_generator.cv')),
            ],
        ),
    ]
