# Generated by Django 5.2.7 on 2025-11-07 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0006_alter_education_options_cv_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technique', 'Compétence Technique'), ('soft', 'Compétence Interpersonnelle'), ('outil', 'Outil / Logiciel')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_generator.cv'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
