# Generated by Django 6.0.2 on 2026-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0005_remove_funddeposit_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddeposit',
            name='interest_earned',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Intérêts cumulés versés (FCFA)'),
        ),
        migrations.AlterField(
            model_name='funddeposit',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('withdrawn', 'Retiré')], default='active', max_length=10),
        ),
    ]
