# Generated by Django 6.0.2 on 2026-07-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0006_alter_funddeposit_interest_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='presence',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('excused', 'Absence Signalée')], default='present', max_length=10, verbose_name='Présence'),
        ),
    ]
