# Generated by Django 6.0.2 on 2026-07-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0007_contribution_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cash_returned_manual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Retour en caisse (FCFA)'),
        ),
        migrations.AddField(
            model_name='session',
            name='loan_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date butoire de remboursement'),
        ),
        migrations.AddField(
            model_name='session',
            name='loan_fund_available',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Fond disponible pour prêt (FCFA)'),
        ),
        migrations.AddField(
            model_name='session',
            name='loan_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Taux d'intérêt (%)"),
        ),
        migrations.AddField(
            model_name='session',
            name='main_raised_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Main levée de la séance (FCFA)'),
        ),
    ]
