# Generated by Django 6.0.2 on 2026-07-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0008_session_cash_returned_manual_session_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='repayment_amount_manual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant remboursements (FCFA)'),
        ),
    ]
