# Generated by Django 6.0.2 on 2026-07-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0009_session_repayment_amount_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='repayment_members_manual',
            field=models.TextField(blank=True, verbose_name='Membres remboursant (séparés par des virgules)'),
        ),
    ]
