# Generated by Django 6.0.2 on 2026-07-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0010_session_repayment_members_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_granted', to='njangi.session'),
        ),
    ]
