# Generated by Django 6.0.2 on 2026-07-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0011_loan_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddeposit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='njangi.session', verbose_name='Séance associée'),
        ),
    ]
