# Generated by Django 6.0.2 on 2026-07-11 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0012_funddeposit_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='njangi.session'),
        ),
        migrations.CreateModel(
            name='SessionBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Montant de la main (FCFA)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_shares', to='njangi.membership')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_beneficiaries', to='njangi.session')),
            ],
            options={
                'verbose_name': 'Bénéficiaire de séance',
                'verbose_name_plural': 'Bénéficiaires de séances',
                'unique_together': {('session', 'membership')},
            },
        ),
    ]
