# Generated by Django 6.0.2 on 2026-07-11 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0013_loanrepayment_session_sessionbeneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='base_fund_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Solde du fond de caisse (FCFA)'),
        ),
        migrations.AlterField(
            model_name='fundtransaction',
            name='type',
            field=models.CharField(choices=[('deposit_in', 'Dépôt entrant'), ('deposit_out', 'Retrait dépôt'), ('loan_out', 'Prêt accordé'), ('repayment', 'Remboursement prêt'), ('interest_in', 'Intérêts prêt reçus'), ('interest_out', 'Intérêts dépôt versés'), ('penalty_in', 'Pénalités encaissées'), ('hand_paid', 'Main versée au bénéficiaire'), ('expense', 'Dépense du groupe'), ('adjustment', 'Ajustement manuel'), ('base_fund_in', 'Versement fond de caisse'), ('base_fund_out', 'Retrait fond de caisse')], max_length=15),
        ),
        migrations.CreateModel(
            name='BaseFundDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Montant versé (FCFA)')),
                ('deposited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_fund_deposits', to='njangi.membership')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_fund_deposits', to='njangi.session', verbose_name='Séance associée')),
            ],
            options={
                'verbose_name': 'Versement fond de caisse',
                'verbose_name_plural': 'Versements fond de caisse',
                'ordering': ['-deposited_at'],
            },
        ),
    ]
