# Generated by Django 6.0.2 on 2026-07-11 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0014_membership_base_fund_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFundWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Montant retiré (FCFA)')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif du retrait (événement)')),
                ('withdrawn_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_fund_withdrawals', to='njangi.membership')),
            ],
            options={
                'verbose_name': 'Retrait fond de caisse',
                'verbose_name_plural': 'Retraits fond de caisse',
                'ordering': ['-withdrawn_at'],
            },
        ),
    ]
