# Generated by Django 6.0.2 on 2026-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0015_basefundwithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Chaque semaine'), ('biweekly', 'Deux fois par mois'), ('monthly', 'Chaque mois'), ('quarterly', 'Tous les 3 mois (trimestriel)')], default='monthly', max_length=10, verbose_name='Fréquence des séances'),
        ),
    ]
