# Generated by Django 6.0.2 on 2026-09-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0017_session_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='meeting_type',
            field=models.CharField(choices=[('sport', 'Sport'), ('church', 'Église'), ('students', 'Étudiants'), ('family', 'Famille'), ('other', 'Autre')], default='other', max_length=12, verbose_name='Type de réunion'),
        ),
    ]
