# Generated by Django 6.0.2 on 2026-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchaslucpay_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='national_id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
