# Generated by Django 6.0.7 on 2026-07-31 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='✨', max_length=10, verbose_name='Emoji / icône')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'établissement")),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('kind', models.CharField(choices=[('salon', 'Salon de coiffure'), ('institut', 'Institut de beauté'), ('spa', 'Spa & bien-être'), ('barbier', 'Barbershop')], default='salon', max_length=10, verbose_name="Type d'établissement")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse complète')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Numéro WhatsApp (format international, ex: 237690000000)')),
                ('phone_display', models.CharField(blank=True, max_length=20, verbose_name='Téléphone affiché')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salons/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='salons/covers/', verbose_name='Photo de couverture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible sur la plateforme')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Établissement vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to='salonhub_salons.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_verified', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Prestation')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salonhub_salons.salon')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermé ce jour')),
                ('start_time', models.TimeField(default='08:00', verbose_name='Ouverture')),
                ('end_time', models.TimeField(default='18:00', verbose_name='Fermeture')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='salonhub_salons.salon')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('salon', 'weekday')},
            },
        ),
    ]
