# Generated by Django 6.0.2 on 2026-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonhub_salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='kind',
            field=models.CharField(choices=[('coiffure', 'Coiffure & Esthétique'), ('beaute', 'Institut de Beauté & Spa'), ('elec', 'Électricité & Énergie'), ('plomb', 'Plomberie & Sanitaire'), ('meca', 'Mécanique & Auto'), ('batiment', 'Maçonnerie & Bâtiment'), ('couture', 'Couture & Mode'), ('menuis', 'Menuiserie & Ameublement'), ('peinture', 'Peinture & Décoration'), ('autre', 'Autre Service'), ('salon', 'Coiffure & Esthétique'), ('institut', 'Institut de Beauté & Spa'), ('spa', 'Spa & bien-être'), ('barbier', 'Barbershop')], default='coiffure', max_length=10, verbose_name="Secteur d'activité"),
        ),
    ]
