"""Editorial bank: seven original themes, each covering four skills (28 days)."""


def q(prompt, choices, answer, evidence, explanation):
    return {"prompt": prompt, "options": dict(zip("ABCD", choices)), "answer": answer,
            "evidence": evidence, "explanation": explanation}


TOPICS = [
    {"title": "Une bibliothèque qui change ses horaires", "event": "une visite de la bibliothèque des Érables",
     "debate": "Document 1 — Nadia : Ouvrir les bibliothèques le dimanche permettrait aux salariés de venir avec leurs enfants. Les bâtiments existent déjà ; mieux utiliser ces espaces serait plus utile que créer de nouveaux équipements.\n\nDocument 2 — Luc : Une ouverture dominicale suppose de financer du personnel supplémentaire. Avant d'étendre les horaires, il faudrait améliorer les services proposés pendant la semaine et consulter les agents concernés.",
     "eo": "Les bibliothèques devraient-elles ouvrir tous les jours ? Présentez votre point de vue et justifiez-le.",
     "ce": {"document": "Bibliothèque des Érables — Avis aux lecteurs\nÀ partir du 15 novembre, la bibliothèque restera ouverte jusqu'à 20 heures le mercredi. Les autres jours, elle fermera à 18 heures, comme auparavant. Cette expérimentation durera trois mois ; son maintien dépendra de la fréquentation observée. Le prêt des livres et le retour des documents seront possibles pendant toute la soirée. En revanche, l'espace jeunesse fermera toujours à 18 heures, faute de personnel disponible. L'accès aux ordinateurs nécessitera une réservation, à effectuer au plus tard la veille. Les lecteurs qui souhaitent seulement consulter les journaux pourront venir sans réserver. Une boîte située près de la sortie recueillera les suggestions concernant ces nouveaux horaires.",
     "questions": [q("Quel changement est annoncé ?", ["Une ouverture plus tardive chaque jour", "Une ouverture jusqu'à 20 heures le mercredi", "La fermeture du mercredi", "Une ouverture le dimanche"], "B", "jusqu'à 20 heures le mercredi", "Le prolongement concerne uniquement le mercredi. Ni le dimanche ni une fermeture du mercredi ne sont annoncés."), q("Que peut faire un lecteur mercredi à 19 heures sans réservation ?", ["Utiliser un ordinateur", "Entrer dans l'espace jeunesse", "Consulter les journaux", "Assister à un atelier pour enfants"], "C", "consulter les journaux pourront venir sans réserver", "Les ordinateurs doivent être réservés et l'espace jeunesse est fermé ; aucun atelier n'est annoncé."), q("À quelle condition les nouveaux horaires seront-ils conservés ?", ["Si suffisamment de lecteurs viennent", "Si tous les lecteurs réservent", "Si la boîte à suggestions est retirée", "Si le prêt des livres est supprimé"], "A", "son maintien dépendra de la fréquentation observée", "La décision dépend de la fréquentation, pas des réservations ni d'une suppression de services.")]},
     "co": {"document": "Bonjour, je vous appelle au sujet de ma réservation à la bibliothèque. J'avais demandé un ordinateur pour mercredi à dix-neuf heures, mais je dois accompagner ma fille à son cours de musique. Pourrais-je venir vendredi à la même heure ? Vendredi, nous fermons à dix-huit heures. Je peux vous proposer dix-sept heures, ou mercredi prochain à dix-neuf heures. Dans ce cas, je préfère mercredi prochain. Est-ce que je dois remplir une nouvelle demande ? Non, je déplace votre réservation. Pensez simplement à apporter votre carte de lecteur. Très bien. Une dernière question : puis-je rendre mes livres aujourd'hui même si la bibliothèque est fermée ? Oui, vous pouvez utiliser la boîte de retour extérieure. Merci, cela m'évitera de les garder une semaine de plus.",
     "questions": [q("Pourquoi la lectrice souhaite-t-elle modifier sa réservation ?", ["Son ordinateur est cassé", "Elle a perdu sa carte", "Elle accompagne sa fille", "La bibliothèque ferme mercredi"], "C", "je dois accompagner ma fille à son cours de musique", "La contrainte est familiale ; la bibliothèque reste ouverte mercredi."), q("Quelle nouvelle réservation est finalement retenue ?", ["Vendredi à dix-sept heures", "Mercredi prochain à dix-neuf heures", "Vendredi à dix-neuf heures", "Aujourd'hui à dix-huit heures"], "B", "je préfère mercredi prochain", "Vendredi à dix-sept heures est proposé mais refusé ; dix-neuf heures vendredi est impossible."), q("Comment peut-elle rendre ses livres aujourd'hui ?", ["En remplissant une nouvelle demande", "En attendant un employé", "En les donnant au professeur de musique", "En utilisant une boîte extérieure"], "D", "utiliser la boîte de retour extérieure", "La boîte permet le retour même lorsque la bibliothèque est fermée.")]}},
    {"title": "Un atelier numérique accessible", "event": "un atelier d'initiation aux outils numériques",
     "debate": "Document 1 — Karim : Les ateliers numériques gratuits rendent les démarches plus accessibles. Apprendre avec un accompagnateur permet de gagner en autonomie et de ne plus dépendre systématiquement de ses proches.\n\nDocument 2 — Élise : Un atelier ne résout pas toutes les difficultés. Certaines personnes n'ont pas d'équipement ou préfèrent un accueil humain. Les services devraient conserver un guichet plutôt que tout imposer en ligne.",
     "eo": "Faut-il proposer toutes les démarches du quotidien uniquement sur Internet ? Justifiez votre réponse.",
     "ce": {"document": "La maison de quartier propose un atelier pour apprendre à envoyer des pièces jointes et à reconnaître les courriels suspects. La séance aura lieu samedi de 9 heures à 11 heures. Elle est gratuite, mais limitée à douze participants. Les inscriptions sont ouvertes jusqu'à jeudi soir. Les personnes qui possèdent un ordinateur portable peuvent l'apporter ; trois appareils seront aussi prêtés sur place, sur demande au moment de l'inscription. Aucun mot de passe personnel ne sera demandé par l'animateur. Les exercices utiliseront des comptes fictifs. Les débutants sont prioritaires. Les personnes déjà à l'aise avec le courrier électronique sont invitées à participer à un autre atelier, consacré aux tableurs, le mois suivant.",
     "questions": [q("À qui cet atelier s'adresse-t-il en priorité ?", ["Aux débutants", "Aux animateurs expérimentés", "Aux spécialistes des tableurs", "Aux vendeurs d'ordinateurs"], "A", "Les débutants sont prioritaires", "Le prochain atelier de tableurs est distinct de cette séance destinée aux débutants."), q("Comment obtenir un ordinateur prêté ?", ["Payer un supplément samedi", "Communiquer son mot de passe", "Le demander lors de l'inscription", "Attendre le mois suivant"], "C", "sur demande au moment de l'inscription", "Le prêt doit être demandé à l'inscription ; ni supplément ni mot de passe n'est requis."), q("Quelle précaution protège les participants ?", ["L'enregistrement de leurs messages privés", "L'utilisation de comptes fictifs", "L'obligation d'apporter un ordinateur", "La fermeture des inscriptions samedi"], "B", "Les exercices utiliseront des comptes fictifs", "Les comptes fictifs évitent d'utiliser les données personnelles. Les inscriptions ferment jeudi.")]},
     "co": {"document": "Bonjour, je voudrais inscrire mon père à votre atelier numérique. Il sait consulter ses messages, mais il ne sait pas envoyer de document. C'est justement un point que nous travaillerons samedi. A-t-il un ordinateur portable ? Oui, mais sa batterie ne fonctionne plus. Ce n'est pas un problème s'il apporte son chargeur. Sinon, nous pouvons lui prêter un appareil. Je vais demander un prêt : ce sera plus simple pour lui. D'accord, il reste un appareil disponible. Je le réserve à son nom. Dois-je lui écrire ses mots de passe sur une feuille ? Non, surtout pas. Nous utiliserons des comptes d'entraînement. Votre père doit seulement venir un quart d'heure avant le début pour s'installer tranquillement.",
     "questions": [q("Quelle difficulté le père veut-il surmonter ?", ["Allumer son ordinateur", "Envoyer un document", "Lire ses messages", "Créer un tableur"], "B", "il ne sait pas envoyer de document", "Il sait déjà consulter ses messages ; le problème concerne les documents joints."), q("Quel matériel utilisera-t-il finalement ?", ["Son ordinateur avec un chargeur", "Le téléphone de l'animateur", "Un appareil prêté", "Un ordinateur acheté sur place"], "C", "Je vais demander un prêt", "Le chargeur est une possibilité évoquée, mais le choix final est le prêt."), q("Que doit-il apporter pour les comptes utilisés ?", ["Aucun mot de passe personnel", "Tous ses mots de passe", "Une copie de ses messages", "Une nouvelle adresse payante"], "A", "Nous utiliserons des comptes d'entraînement", "L'animateur exclut expressément les mots de passe personnels.")]}},
    {"title": "Une ligne de bus réorganisée", "event": "une réunion de quartier consacrée aux transports",
     "debate": "Document 1 — Samira : Des bus fréquents facilitent les déplacements de ceux qui ne conduisent pas. Réduire leur prix attirerait davantage d'usagers et limiterait le nombre de voitures en centre-ville.\n\nDocument 2 — Paul : La gratuité ne suffit pas si les trajets sont trop longs. Il faudrait d'abord améliorer les correspondances et la ponctualité, même si cela oblige à maintenir un prix raisonnable.",
     "eo": "Pour encourager les transports publics, faut-il les rendre gratuits ? Expliquez votre point de vue.",
     "ce": {"document": "Pendant les travaux de la rue des Tilleuls, la ligne 8 sera déviée du 3 au 14 juin inclus. L'arrêt Marché ne sera pas desservi ; les voyageurs devront utiliser l'arrêt Mairie, situé à deux cents mètres. La fréquence des bus sera conservée aux heures de pointe. En milieu de journée, le détour pourra entraîner un retard de cinq minutes. Les horaires affichés à l'arrêt Mairie correspondent au passage habituel et ne tiennent pas compte de ce retard éventuel. Les billets achetés avant les travaux resteront valables. Une navette gratuite sera proposée le samedi matin entre la Mairie et le marché, afin d'aider les personnes qui ont des difficultés à marcher.",
     "questions": [q("Quel arrêt remplace l'arrêt Marché pendant les travaux ?", ["Tilleuls", "Gare", "Centre", "Mairie"], "D", "utiliser l'arrêt Mairie", "Le remplacement annoncé est Mairie ; les autres arrêts ne sont pas proposés."), q("Que faut-il prévoir en milieu de journée ?", ["Une suppression de tous les bus", "Un retard possible de cinq minutes", "Un billet supplémentaire", "Une fréquence plus élevée"], "B", "un retard de cinq minutes", "Le retard est possible ; il n'est pas question de supprimer le service ni d'acheter un nouveau billet."), q("Quand la navette gratuite circule-t-elle ?", ["Chaque soir", "Du lundi au vendredi", "Le samedi matin", "Seulement après le 14 juin"], "C", "le samedi matin", "Le dispositif est limité au samedi matin pendant les travaux.")]},
     "co": {"document": "Excusez-moi, ce bus passe-t-il encore devant le marché ? Pas cette semaine : nous passons par la Mairie à cause des travaux. Vous devrez marcher environ deux cents mètres. J'ai un panier assez lourd. Y a-t-il une autre solution ? Si vous voyagez samedi matin, une navette vous déposera directement au marché. Mais aujourd'hui, mercredi, elle ne circule pas. Je comprends. Je vais donc descendre à la Mairie. Mon ticket a été acheté avant le début des travaux ; est-il toujours valable ? Oui, vous n'avez rien à racheter. Merci. Vous pensez que nous serons à l'heure ? À cette heure-ci, le détour peut nous faire perdre quelques minutes. Si vous avez un rendez-vous précis, prévoyez une petite marge.",
     "questions": [q("Quel jour cet échange a-t-il lieu ?", ["Samedi", "Mercredi", "Dimanche", "Vendredi"], "B", "aujourd'hui, mercredi", "Samedi est évoqué pour la navette, mais l'échange a lieu mercredi."), q("Quelle solution le voyageur choisit-il ?", ["Attendre la navette aujourd'hui", "Acheter un nouveau ticket", "Descendre à la Mairie", "Descendre devant le marché"], "C", "Je vais donc descendre à la Mairie", "La navette ne circule pas ce jour-là et l'arrêt du marché n'est pas desservi."), q("Quel conseil le conducteur donne-t-il ?", ["Prévoir du temps supplémentaire", "Voyager sans ticket", "Revenir après les travaux", "Éviter tout rendez-vous"], "A", "prévoyez une petite marge", "Il conseille une marge à cause du détour, pas d'annuler le rendez-vous.")]}},
    {"title": "Une formation compatible avec le travail", "event": "une journée de découverte d'un centre de formation",
     "debate": "Document 1 — Ana : Les cours en ligne permettent aux salariés de se former sans quitter leur emploi. La souplesse des horaires et la possibilité de revoir les explications favorisent un apprentissage régulier.\n\nDocument 2 — Marc : Apprendre seul demande une discipline difficile à maintenir. Les échanges en classe permettent de poser des questions immédiatement et de bénéficier du soutien d'un groupe.",
     "eo": "Apprend-on aussi bien en ligne qu'en présentiel ? Donnez votre avis avec des exemples.",
     "ce": {"document": "Le centre Horizon ouvre une session de français professionnel de huit semaines. Les cours se dérouleront les mardis et jeudis de 18 heures à 20 heures. Chaque candidat passera un entretien de positionnement gratuit avant de confirmer son inscription. Cet entretien ne constitue pas un examen et sert uniquement à choisir le groupe adapté. Une absence par semaine est tolérée si le participant consulte ensuite les supports mis en ligne. Les séances ne seront pas enregistrées, mais des exercices de révision seront accessibles jusqu'à un mois après la fin de la formation. Les demandes d'inscription doivent être envoyées avant le 20 août. Un paiement en deux fois peut être demandé ; il n'est pas automatique.",
     "questions": [q("À quoi sert l'entretien de positionnement ?", ["À obtenir un diplôme", "À sélectionner le groupe adapté", "À fixer les horaires", "À supprimer les exercices"], "B", "choisir le groupe adapté", "L'entretien n'est pas un examen délivrant un diplôme."), q("Que doit faire un participant après une absence tolérée ?", ["Payer une pénalité", "Recommencer huit semaines", "Consulter les supports en ligne", "Regarder un enregistrement du cours"], "C", "consulte ensuite les supports mis en ligne", "Les séances ne sont pas enregistrées ; le rattrapage passe par les supports."), q("Quelle possibilité faut-il demander expressément ?", ["L'entretien gratuit", "Le choix automatique des horaires", "La suppression des absences", "Le paiement en deux fois"], "D", "Un paiement en deux fois peut être demandé", "Le paiement fractionné est possible sur demande, mais pas automatique.")]},
     "co": {"document": "Bonjour, j'aimerais suivre vos cours du soir, mais je travaille jusqu'à dix-huit heures le mardi. Puis-je arriver un peu plus tard ? Un retard occasionnel est possible. En revanche, si vous manquez systématiquement la première partie du cours, cette session ne vous conviendra pas. Mon employeur pourrait m'autoriser à partir plus tôt pendant huit semaines. Je vais lui demander. Très bien. Voulez-vous déjà prendre rendez-vous pour l'entretien de positionnement ? Oui, mais je ne souhaite pas payer avant d'avoir sa réponse. L'entretien est gratuit et ne vous engage pas à vous inscrire. Alors, prenons rendez-vous. Et si je ne peux pas rejoindre cette session ? Nous pourrons vous informer de la prochaine, mais ses horaires ne sont pas encore fixés.",
     "questions": [q("Quelle difficulté rencontre le candidat ?", ["Il travaille jusqu'au début du cours", "Il habite dans un autre pays", "Il refuse un entretien", "Il a déjà payé deux fois"], "A", "je travaille jusqu'à dix-huit heures le mardi", "Le problème est la compatibilité des horaires."), q("Quelle démarche accepte-t-il de faire maintenant ?", ["Payer la totalité", "S'inscrire définitivement", "Prendre rendez-vous pour l'entretien", "Choisir les prochains horaires"], "C", "Alors, prenons rendez-vous", "Il accepte un entretien gratuit, sans inscription définitive."), q("Que sait-on de la prochaine session ?", ["Elle sera uniquement en ligne", "Ses horaires restent à déterminer", "Elle sera gratuite", "Elle durera un mois"], "B", "ses horaires ne sont pas encore fixés", "Aucune durée, gratuité ou modalité en ligne n'est annoncée.")]}},
    {"title": "Un logement partagé", "event": "une rencontre d'information sur la colocation",
     "debate": "Document 1 — Inès : La colocation réduit les dépenses et aide à créer des liens dans une nouvelle ville. Avec des règles discutées à l'avance, partager un logement peut devenir une expérience enrichissante.\n\nDocument 2 — Thomas : Partager son logement limite l'intimité. Même lorsque les règles sont claires, les rythmes de vie différents peuvent provoquer des conflits. Un logement individuel offre davantage de tranquillité.",
     "eo": "La colocation est-elle une bonne solution lorsqu'on s'installe dans une nouvelle ville ? Justifiez votre réponse.",
     "ce": {"document": "Annonce fictive — Une chambre se libère dans une colocation de trois personnes près de la gare. Le loyer annoncé comprend Internet, mais pas les dépenses d'électricité, réparties chaque mois entre les habitants. La chambre est meublée ; les meubles ne peuvent pas être retirés, faute d'espace de stockage. Les colocataires recherchent une personne qui accepte de participer au ménage des parties communes selon un planning discuté ensemble. Le travail à domicile est possible, à condition de ne pas organiser de réunions dans le salon partagé. Les visites auront lieu samedi après-midi sur rendez-vous. La chambre sera disponible dès le début du mois prochain ; aucune entrée anticipée ne pourra être proposée.",
     "questions": [q("Quelle dépense est incluse dans le loyer annoncé ?", ["L'électricité", "Internet", "Les repas", "Le ménage professionnel"], "B", "comprend Internet", "L'électricité est facturée séparément ; repas et ménage professionnel ne sont pas annoncés."), q("Quelle condition concerne le travail à domicile ?", ["Travailler uniquement le samedi", "Retirer les meubles", "Ne pas tenir de réunions dans le salon", "Payer tout le loyer seul"], "C", "ne pas organiser de réunions dans le salon partagé", "Le travail à domicile est autorisé avec cette limite précise."), q("Quand un emménagement est-il possible ?", ["Immédiatement", "Avant la visite", "Seulement dans trois mois", "Au début du mois prochain"], "D", "dès le début du mois prochain", "L'annonce exclut une entrée anticipée.")]},
     "co": {"document": "Bonjour, je vous appelle pour la chambre près de la gare. Je commence mon travail lundi prochain et j'aurais aimé emménager dimanche. La chambre n'est libre qu'au début du mois suivant. Je suis désolée, nous ne pouvons pas avancer cette date. Je pourrais loger chez un ami en attendant. Est-il possible de visiter samedi ? Oui, à quinze heures ou à seize heures trente. À quinze heures, je serai encore dans le train ; je choisis donc seize heures trente. Très bien. Je travaille parfois de chez moi. Cela vous dérange-t-il ? Pas du tout, si vos réunions se déroulent dans votre chambre. Nous souhaitons garder le salon disponible pour tout le monde. C'est compris. Je vous confirme ma venue samedi à seize heures trente.",
     "questions": [q("Pourquoi le candidat ne peut-il pas emménager dimanche ?", ["Il n'a pas de travail", "La chambre n'est pas encore libre", "La gare est fermée", "Il refuse de visiter"], "B", "La chambre n'est libre qu'au début du mois suivant", "La date de disponibilité empêche l'entrée anticipée."), q("À quelle heure la visite est-elle confirmée ?", ["Quinze heures", "Dix-huit heures", "Seize heures trente", "Midi"], "C", "samedi à seize heures trente", "Quinze heures est une première proposition que le candidat ne peut pas accepter."), q("Où devra-t-il tenir ses réunions à distance ?", ["Dans sa chambre", "Dans le salon", "À la gare", "Chez tous ses colocataires"], "A", "vos réunions se déroulent dans votre chambre", "Le salon doit rester disponible pour les autres habitants.")]}},
    {"title": "Une association cherche des bénévoles", "event": "une journée de bénévolat dans une association locale",
     "debate": "Document 1 — Léa : Le bénévolat permet de découvrir des personnes différentes et d'agir concrètement dans son quartier. Même quelques heures par mois peuvent être utiles lorsqu'elles répondent à un besoin précis.\n\nDocument 2 — Youssef : Le bénévolat ne devrait pas remplacer des emplois nécessaires. Une association doit former ses bénévoles et respecter leur disponibilité, sans faire reposer tout son fonctionnement sur leur bonne volonté.",
     "eo": "Est-il utile d'encourager les jeunes à faire du bénévolat ? Développez votre point de vue.",
     "ce": {"document": "L'association Main ouverte recherche des bénévoles pour préparer des colis alimentaires le vendredi matin. Aucune expérience n'est exigée : une séance d'accueil présentera les règles d'hygiène et l'organisation du travail. Les personnes inscrites devront toutefois pouvoir rester toute la matinée, de 8 heures à 12 heures, afin de ne pas interrompre la préparation des commandes. Les candidats indisponibles le vendredi pourront aider au classement des dons le mercredi après-midi. Cette seconde activité accepte des présences plus courtes, à partir d'une heure. Les deux activités nécessitent une inscription préalable. L'association ne demande pas d'engagement annuel, mais souhaite être prévenue au moins deux jours avant une absence prévue.",
     "questions": [q("Quelle disponibilité est nécessaire pour préparer les colis ?", ["Une heure le mercredi", "Toute la matinée du vendredi", "Tous les jours", "Une année complète"], "B", "de 8 heures à 12 heures", "La préparation demande la matinée entière ; l'heure minimale concerne le classement du mercredi."), q("Quelle activité convient à une personne disponible seulement une heure ?", ["Le classement des dons le mercredi", "La préparation du vendredi", "Une livraison nocturne", "La séance quotidienne d'hygiène"], "A", "à partir d'une heure", "Les présences courtes sont admises pour le classement du mercredi."), q("Que demande l'association en cas d'absence prévue ?", ["Trouver obligatoirement un remplaçant", "Payer les colis", "Prévenir deux jours à l'avance", "S'engager pour une année"], "C", "prévenue au moins deux jours avant", "Il faut prévenir ; aucun paiement ni remplaçant obligatoire n'est mentionné.")]},
     "co": {"document": "Bonjour, j'aimerais aider votre association le vendredi, mais je dois partir à dix heures trente pour chercher mon enfant. Pour préparer les colis, nous avons besoin de personnes présentes jusqu'à midi. En revanche, le classement des dons du mercredi est plus souple. Le mercredi après-midi, je suis libre entre quatorze et seize heures. Cela conviendrait très bien. Dois-je venir chaque semaine ? Pas nécessairement. Nous fixons vos dates ensemble, puis nous vous demandons de prévenir si vous ne pouvez pas venir. Je préférerais commencer une semaine sur deux. Aucun problème. Avant votre première séance, nous prendrons quelques minutes pour vous expliquer comment trier les objets. Je pensais devoir déjà connaître le fonctionnement d'une association. Non, nous vous accompagnerons au début.",
     "questions": [q("Pourquoi l'activité du vendredi ne convient-elle pas ?", ["La personne n'a aucune expérience", "L'association ferme à dix heures", "La personne doit partir avant midi", "Il faut venir chaque jour"], "C", "je dois partir à dix heures trente", "La matinée entière est requise ; l'expérience n'est pas une condition."), q("Quelle fréquence la personne propose-t-elle ?", ["Chaque jour", "Une semaine sur deux", "Une fois par an", "Deux fois par jour"], "B", "commencer une semaine sur deux", "Cette proposition est acceptée ; une présence hebdomadaire n'est pas imposée."), q("Comment sera-t-elle aidée au début ?", ["Par une explication du tri", "Par un examen obligatoire", "Par une formation payante", "Par une suppression des tâches"], "A", "vous expliquer comment trier les objets", "L'association prévoit un accompagnement, sans exiger d'expérience préalable.")]}},
    {"title": "Une organisation de travail hybride", "event": "une rencontre sur l'organisation du travail hybride",
     "debate": "Document 1 — Amélie : Le télétravail réduit les déplacements et facilite la concentration. Laisser les salariés choisir certains jours à distance montre qu'on leur fait confiance et peut améliorer leur satisfaction.\n\nDocument 2 — Nicolas : Les échanges spontanés sont plus difficiles à distance. Pour accompagner les nouveaux collègues et résoudre les problèmes collectifs, des jours communs au bureau restent indispensables.",
     "eo": "Le télétravail devrait-il être proposé à tous les salariés dont l'activité le permet ? Donnez votre avis.",
     "ce": {"document": "Dans cette entreprise fictive, une nouvelle organisation sera testée pendant deux mois. Les salariés volontaires pourront travailler à distance deux jours par semaine, avec l'accord de leur responsable. Le mardi restera une journée commune au bureau pour faciliter les réunions d'équipe. Les autres jours seront choisis selon les besoins du service, et non imposés de façon identique à tous. Les nouveaux salariés passeront leurs deux premières semaines sur place afin de rencontrer leurs collègues et de découvrir les outils utilisés. À la fin du test, un questionnaire recueillera les avis. La direction décidera ensuite si l'organisation est maintenue, modifiée ou abandonnée. Aucune décision définitive n'est donc prise à ce stade.",
     "questions": [q("Quelle journée reste commune au bureau ?", ["Le lundi", "Le jeudi", "Le mardi", "Le vendredi"], "C", "Le mardi restera une journée commune au bureau", "Une seule journée commune est précisément désignée."), q("Quelle règle concerne les nouveaux salariés ?", ["Ils télétravaillent immédiatement", "Ils restent deux semaines sur place", "Ils ne peuvent jamais télétravailler", "Ils choisissent seuls toutes les règles"], "B", "leurs deux premières semaines sur place", "La présence initiale est temporaire et destinée à l'intégration."), q("Que décidera la direction après le test ?", ["Elle évaluera plusieurs suites possibles", "Elle imposera déjà cinq jours à distance", "Elle supprimera les questionnaires", "Elle prolongera automatiquement le dispositif"], "A", "maintenue, modifiée ou abandonnée", "Le maintien n'est pas automatique ; plusieurs décisions restent possibles.")]},
     "co": {"document": "J'aimerais travailler à distance le mardi et le jeudi. Le mardi doit rester une journée au bureau : c'est notre moment commun avec l'équipe. Vous pourriez choisir le lundi ou le vendredi à la place. Le lundi conviendrait mieux, puisque je dois souvent rencontrer un client le vendredi. D'accord pour lundi et jeudi, à partir du mois prochain. Je pensais que cela commencerait dès la semaine prochaine. Non, nous devons d'abord installer votre accès sécurisé. En attendant, gardez votre organisation actuelle. Est-ce que je dois acheter un nouvel ordinateur ? Non, le service vous prêtera le matériel nécessaire. Nous ferons le point après deux mois pour voir si ce rythme facilite votre travail et celui de l'équipe.",
     "questions": [q("Quels jours sont finalement choisis à distance ?", ["Mardi et jeudi", "Lundi et jeudi", "Jeudi et vendredi", "Lundi et vendredi"], "B", "D'accord pour lundi et jeudi", "Le mardi est exclu et le vendredi ne convient pas au salarié."), q("Pourquoi le dispositif ne commence-t-il pas immédiatement ?", ["Le salarié doit changer de client", "Le bureau est fermé", "Un accès sécurisé doit être installé", "Le salarié doit acheter du matériel"], "C", "installer votre accès sécurisé", "L'installation technique explique le délai ; l'ordinateur sera prêté."), q("Quand une évaluation est-elle prévue ?", ["Après deux mois", "Dès le lendemain", "Après une année", "Avant chaque réunion"], "A", "Nous ferons le point après deux mois", "Le bilan est prévu à la fin des deux premiers mois.")]}},
]

for topic in TOPICS:
    topic["ee"] = {
        "1": f"Vous souhaitez participer à {topic['event']} avec un ami. Écrivez-lui un message : expliquez ce que vous voulez faire, proposez une date et un lieu de rendez-vous, et demandez-lui de confirmer sa disponibilité. Vous pouvez inventer les informations pratiques. Écrivez de 60 à 120 mots.",
        "2": f"Vous avez participé à {topic['event']}. Pour le blog de votre quartier, racontez le déroulement de cette expérience, décrivez ce qui vous a marqué et expliquez pourquoi vous recommanderiez ou non cette activité. Écrivez de 120 à 150 mots.",
        "3": "Vous publiez un article sur le thème du jour. Présentez les deux points de vue des documents avec vos propres mots (40 à 60 mots), puis donnez votre opinion argumentée (80 à 120 mots). L'ensemble de votre texte doit comporter entre 120 et 180 mots.",
    }


TOPIC_LESSONS = [
    {"ce": ("Lire un avis : règle générale et exception", "Dans un avis de service, les horaires de fermeture, les espaces ouverts et les conditions de réservation peuvent différer. Classe chaque information par service plutôt que d'appliquer une seule règle à tout le bâtiment."),
     "co": ("Suivre une réservation qui change", "Dans un échange de réservation, plusieurs créneaux sont souvent proposés. Attends la confirmation finale pour retenir le rendez-vous ; distingue une proposition de ce qui est réellement accepté."),
     "ee": ("Présenter une sortie culturelle clairement", "Un lecteur doit pouvoir comprendre le programme sans te poser de nouvelles questions. Pour un message, précise les informations pratiques ; pour un récit, relie une observation concrète à ton appréciation."),
     "eo": ("Argumenter sur l'accès à la culture", "Construis une raison liée aux usagers et une autre liée à l'organisation. Un exemple précis rend l'argument crédible ; une concession sur les coûts peut nuancer ton avis sans l'annuler.")},
    {"ce": ("Repérer le public visé et les modalités", "Une annonce d'atelier distingue souvent ce qui est obligatoire de ce qui est facultatif. Repère les formulations de priorité, de possibilité et de demande préalable : elles ne signifient pas la même chose."),
     "co": ("Distinguer une difficulté et sa solution", "Écoute d'abord le besoin de la personne, puis les solutions proposées. Un problème matériel peut avoir plusieurs réponses ; ne confonds pas la première possibilité avec le choix final."),
     "ee": ("Expliquer une activité sans jargon", "Adapte tes mots à quelqu'un qui découvre le numérique. Décris une action concrète et son utilité. Pour comparer deux points de vue, distingue l'autonomie recherchée et les obstacles d'accès."),
     "eo": ("Nuancer une opinion sur le numérique", "Évite de parler de tous les usagers comme s'ils avaient les mêmes besoins. Compare une situation où Internet aide et une situation où un accueil humain reste utile.")},
    {"ce": ("Comprendre une information provisoire", "Dans un avis de travaux, relève la période, le trajet de remplacement et les aménagements particuliers. Une solution proposée certains jours ne s'applique pas forcément au jour du déplacement."),
     "co": ("Séparer les jours évoqués du jour réel", "Un dialogue peut citer un jour futur puis revenir à aujourd'hui. Les marqueurs temporels te permettent de savoir quelle solution est disponible maintenant et laquelle devra attendre."),
     "ee": ("Raconter un échange public avec précision", "Pour raconter une réunion, distingue le problème discuté, les propositions et ton bilan personnel. Ne transforme pas une proposition en décision si ton récit ne l'explique pas."),
     "eo": ("Comparer le prix et la qualité d'un service", "Pour défendre une politique de transport, sépare son objectif et ses moyens. Examine le coût pour l'usager, mais aussi la fréquence, la fiabilité et les correspondances.")},
    {"ce": ("Identifier une possibilité sur demande", "Les mots peut et doit expriment des règles différentes. Dans une annonce de formation, vérifie si une facilité est automatique, accordée sur demande ou soumise à une condition."),
     "co": ("Ne pas confondre entretien et engagement", "Les démarches préparatoires n'engagent pas toujours une inscription. Écoute les expressions de gratuité, de confirmation et de décision encore en attente pour comprendre ce qui est accepté."),
     "ee": ("Organiser un récit d'apprentissage", "Relie la chronologie à ce que tu as appris : une situation initiale, une activité concrète et un résultat. Les connecteurs doivent rendre cette progression lisible plutôt que décorer le texte."),
     "eo": ("Comparer deux façons d'apprendre", "Évalue les modalités selon des critères communs : autonomie, échanges, disponibilité et besoin d'accompagnement. Une préférence devient convaincante lorsqu'elle répond à un profil concret.")},
    {"ce": ("Distinguer ce qui est inclus et ce qui est permis", "Une annonce de logement combine dépenses, équipements et règles de vie. Range ces éléments séparément ; inclus dans le loyer ne signifie pas disponible sans condition."),
     "co": ("Suivre une négociation de date", "Repère les contraintes de chaque interlocuteur. Une date souhaitée n'est pas une date disponible ; la dernière confirmation sert de repère pour résumer l'accord."),
     "ee": ("Formuler un message pratique complet", "Dans un message, garde un ton adapté à ton destinataire. Donne les informations utiles dans un ordre simple, puis formule clairement la réponse que tu attends."),
     "eo": ("Défendre une solution avec ses limites", "Explique l'intérêt du logement partagé, puis les conditions qui le rendent viable. Une limite devient une nuance constructive lorsque tu proposes une manière de la gérer.")},
    {"ce": ("Associer une activité à ses conditions", "Quand une annonce propose plusieurs activités, ne mélange pas leurs horaires et leurs exigences. Fais mentalement une colonne par activité, puis rattache chaque condition à la bonne colonne."),
     "co": ("Comprendre une alternative adaptée", "Un refus de la première proposition peut être suivi d'une solution mieux adaptée. Repère la contrainte initiale, l'alternative et l'accord final au lieu de retenir seulement le refus."),
     "ee": ("Rendre compte d'une expérience utile", "Choisis deux faits précis pour raconter l'activité, puis explique ce qu'ils t'ont appris. Une recommandation doit découler de l'expérience décrite et non d'une formule générale."),
     "eo": ("Argumenter sans idéaliser le bénévolat", "Tu peux défendre l'engagement tout en évoquant la formation, la disponibilité et les limites. Relie chaque idée à un exemple d'activité et au besoin auquel elle répond.")},
    {"ce": ("Différencier un test et une règle définitive", "Les avis d'organisation annoncent parfois une expérimentation. Les mots test, bilan et ensuite montrent que la décision reste ouverte : ne conclus pas que le dispositif sera forcément conservé."),
     "co": ("Retenir l'accord final et sa date de début", "Un échange professionnel peut modifier à la fois les jours retenus et la date de démarrage. Écoute ces deux éléments séparément et vérifie les conditions techniques évoquées."),
     "ee": ("Comparer deux opinions sans les déformer", "Dans la tâche 3, reformule chaque position de façon neutre avant de donner ton avis. Présente un argument de chacun, puis développe une réponse personnelle qui tient compte de leur opposition."),
     "eo": ("Construire une opinion conditionnelle", "Une réponse argumentée peut dépendre du métier ou de la situation. Annonce ta position, explique les conditions qui la rendent valable, puis termine par une recommandation claire.")},
]

for topic, lessons in zip(TOPICS, TOPIC_LESSONS):
    topic["lessons"] = lessons
