# Generated by Django 6.0.2 on 2026-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='ville',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ville cible'),
        ),
    ]
