# Generated by Django 6.0.2 on 2026-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgen', '0002_adcampaign_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='photo_produit',
            field=models.ImageField(blank=True, null=True, upload_to='adgen/products/', verbose_name='Photo du produit'),
        ),
    ]
