# Generated by Django 6.0.2 on 2026-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgen', '0003_adcampaign_photo_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcontent',
            name='ad_video_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Vidéo Publicitaire'),
        ),
    ]
