# Generated by Django 6.0.2 on 2026-08-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgen', '0004_adcontent_ad_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='ancien_prix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ancien prix'),
        ),
    ]
