# Generated by Django 6.0.2 on 2026-09-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgen', '0005_adcampaign_ancien_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='photo_produit_2',
            field=models.ImageField(blank=True, null=True, upload_to='adgen/products/', verbose_name='Photo produit 2'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='photo_produit_3',
            field=models.ImageField(blank=True, null=True, upload_to='adgen/products/', verbose_name='Photo produit 3'),
        ),
    ]
