# Generated by Django 6.0.2 on 2026-09-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgen', '0007_soracreditwallet'),
        ('audio_studio', '0003_alter_voiceoverjob_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adcontent',
            name='studio_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_contents', to='audio_studio.musictrackjob'),
        ),
        migrations.AddField(
            model_name='adcontent',
            name='studio_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_contents', to='audio_studio.voiceoverjob'),
        ),
        migrations.CreateModel(
            name='StudioUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=12)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('request_key', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('reserved', 'En attente'), ('running', 'En cours'), ('consumed', 'Terminé'), ('failed', 'À vérifier'), ('released', 'Restitué')], default='reserved', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adgen.adcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'resource', 'created_at'], name='studio_usage_window')],
                'constraints': [models.UniqueConstraint(fields=('user', 'request_key'), name='studio_request_once')],
            },
        ),
    ]
