# Generated by Django 6.0.2 on 2026-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgen', '0008_adcontent_studio_music_adcontent_studio_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiousage',
            name='is_trial',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
