# Generated by Django 5.2.7 on 2026-03-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='description',
            field=models.TextField(blank=True, help_text="Présentation de l'entreprise"),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Entreprise vérifiée par l'équipe"),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_logos/'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[('BTP', 'BTP / Construction'), ('SANTE', 'Santé / Médical'), ('IT', 'Informatique / Tech'), ('COMPTA', 'Comptabilité / Finance'), ('HOTEL', 'Hôtellerie / Restauration'), ('AGRI', 'Agriculture / Agroalimentaire'), ('INDUSTRIE', 'Industrie / Logistique'), ('EDUCATION', 'Éducation / Formation'), ('COMMERCE', 'Commerce / Vente'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
