# Generated by Django 5.2.7 on 2026-04-21 03:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du template')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=5, verbose_name='Langue')),
                ('subject', models.CharField(help_text='Variables: {company_name}, {contact_name}, {sector_label}, {country_label}', max_length=200, verbose_name="Objet de l'email")),
                ('body_html', models.TextField(help_text='Variables: {company_name}, {contact_name}, {sector_label}, {country_label}', verbose_name='Corps HTML')),
                ('body_text', models.TextField(help_text='Version texte (fallback). Mêmes variables.', verbose_name='Corps texte brut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Email',
                'verbose_name_plural': 'Templates Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Nom du contact')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Poste (ex: DRH, Manager RH)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='Site web')),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture / Agroalimentaire'), ('construction', 'Construction / BTP'), ('tech', 'Technologie / IT'), ('sante', 'Santé / Médical'), ('logistique', 'Transport / Logistique'), ('hotellerie', 'Hôtellerie / Restauration'), ('education', 'Éducation / Formation'), ('finance', 'Finance / Comptabilité'), ('industrie', 'Industrie / Manufacture'), ('commerce', 'Commerce / Vente'), ('services', 'Services aux entreprises'), ('autre', 'Autre')], db_index=True, default='autre', max_length=30, verbose_name='Secteur')),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('FR', 'France'), ('DE', 'Allemagne'), ('BE', 'Belgique'), ('CH', 'Suisse'), ('AU', 'Australie'), ('GB', 'Royaume-Uni'), ('US', 'États-Unis'), ('MA', 'Maroc'), ('SN', 'Sénégal'), ('CI', "Côte d'Ivoire"), ('OTHER', 'Autre')], db_index=True, default='CA', max_length=10, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('opened', 'Email ouvert'), ('replied', 'A répondu'), ('registered', 'Inscrit sur la plateforme'), ('not_interested', 'Pas intéressé'), ('bounce', 'Bounce / Email invalide')], db_index=True, default='new', max_length=20, verbose_name='Statut')),
                ('source', models.CharField(choices=[('manual', 'Ajout manuel'), ('csv_import', 'Import CSV/Excel'), ('ai_search', 'Agent IA'), ('web', 'Recherche web')], default='manual', max_length=20, verbose_name='Source')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=300, verbose_name='Tags')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier contact')),
                ('last_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Recruteur',
                'verbose_name_plural': 'Contacts Recruteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('filter_sectors', models.CharField(blank=True, help_text='Vide = tous. Sinon: agriculture,tech,sante', max_length=500, verbose_name='Secteurs ciblés')),
                ('filter_countries', models.CharField(blank=True, help_text='Vide = tous. Sinon: CA,FR,DE', max_length=200, verbose_name='Pays ciblés')),
                ('filter_status', models.CharField(blank=True, help_text='Défaut: new,contacted. Vide = tous (hors bounce).', max_length=200, verbose_name='Statut contacts ciblés')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Total destinataires')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Envoyés')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='Ouvertures')),
                ('replied_count', models.PositiveIntegerField(default=0, verbose_name='Réponses')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sending', "En cours d'envoi"), ('sent', 'Envoyée'), ('paused', 'En pause')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='outreach.outreachtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Campagne Outreach',
                'verbose_name_plural': 'Campagnes Outreach',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('bounced', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='outreach.outreachcampaign')),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_logs', to='outreach.recruitercontact')),
            ],
            options={
                'verbose_name': 'Log Envoi',
                'verbose_name_plural': 'Logs Envois',
                'ordering': ['-sent_at'],
            },
        ),
    ]
