# Generated by Django 6.0.2 on 2026-05-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_categorie_slug_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=120)),
                ('ville', models.CharField(max_length=100)),
                ('prix_moyen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(default='kg', max_length=30)),
                ('tendance', models.CharField(choices=[('hausse', 'En hausse'), ('stable', 'Stable'), ('baisse', 'En baisse')], default='stable', max_length=20)),
                ('date_releve', models.DateField()),
            ],
            options={
                'verbose_name': 'Prix de marche',
                'verbose_name_plural': 'Prix de marche',
                'ordering': ['ville', 'produit'],
                'indexes': [models.Index(fields=['ville', 'produit'], name='agro_prixma_ville_8c42eb_idx'), models.Index(fields=['date_releve'], name='agro_prixma_date_re_9d0dad_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionAgentIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('agricole', 'Agent agricole'), ('maladies', 'Maladies & photos'), ('marche', 'Agent marche'), ('finance', 'Finance & stock')], max_length=30)),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='agro/ia/%Y/%m/')),
                ('reponse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_agro_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question agent IA',
                'verbose_name_plural': 'Questions agents IA',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='StockProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(default=0)),
                ('seuil_alerte', models.FloatField(default=0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_producteurs', to='agro.produitagro')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_agro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock producteur',
                'verbose_name_plural': 'Stocks producteurs',
                'ordering': ['produit__nom'],
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
