# Generated by Django 6.0.2 on 2026-05-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de conversation',
                'verbose_name_plural': 'Sessions de conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'E-Shelle AI')], max_length=20)),
                ('content', models.TextField()),
                ('module_detected', models.CharField(choices=[('general', 'General'), ('resto', 'Restaurant'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('adgen', 'AdGen'), ('transport', 'Transport'), ('sante', 'Sante'), ('immobilier', 'Immobilier'), ('jobs', 'Jobs'), ('njangi', 'Njangi'), ('fintech', 'Fintech'), ('agro', 'Agro'), ('rencontres', 'Rencontres'), ('quincaillerie', 'Quincaillerie')], default='general', max_length=30)),
                ('redirect_url', models.CharField(blank=True, max_length=300)),
                ('has_image', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversationsession')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
