# Generated by Django 6.0.2 on 2026-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='module_detected',
            field=models.CharField(choices=[('general', 'General'), ('resto', 'Restaurant'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('adgen', 'AdGen'), ('transport', 'Transport'), ('sante', 'Sante'), ('immobilier', 'Immobilier'), ('jobs', 'Jobs'), ('njangi', 'Njangi'), ('fintech', 'Fintech'), ('agro', 'Agro'), ('rencontres', 'Rencontres'), ('quincaillerie', 'Quincaillerie'), ('business_onboarding', 'Inscription prestataire')], default='general', max_length=30),
        ),
    ]
