# Generated by Django 5.2.7 on 2025-11-08 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('study', 'Études'), ('work', 'Travail'), ('pr', 'Résidence permanente'), ('scholarship', 'Bourse')], max_length=32)),
                ('is_scholarship', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('cost_min', models.IntegerField(blank=True, null=True)),
                ('cost_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('eligibility_tags', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', 'deadline', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opps', to='radar.source'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_filter', models.CharField(blank=True, default='', max_length=80)),
                ('category_filter', models.CharField(blank=True, default='', max_length=32)),
                ('min_score', models.IntegerField(default=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['country', 'category'], name='radar_oppor_country_960ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['deadline'], name='radar_oppor_deadlin_e1b0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['score'], name='radar_oppor_score_cac49b_idx'),
        ),
    ]
