# Generated by Django 6.0.2 on 2026-08-01 19:44

from django.db import migrations, models


def update_default_contact_numbers(apps, schema_editor):
    ParametrePlateforme = apps.get_model('dashboard', 'ParametrePlateforme')
    ParametrePlateforme.objects.filter(telephone__in=['', '+237 000 000 000', '+237000000000']).update(
        telephone='+237 680 625 082'
    )
    ParametrePlateforme.objects.filter(whatsapp__in=['', '+237 000 000 000', '+237000000000']).update(
        whatsapp='+237680625082'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametreplateforme',
            name='telephone',
            field=models.CharField(default='+237 680 625 082', max_length=25),
        ),
        migrations.AlterField(
            model_name='parametreplateforme',
            name='whatsapp',
            field=models.CharField(default='+237680625082', max_length=25),
        ),
        migrations.RunPython(update_default_contact_numbers, migrations.RunPython.noop),
    ]
