# Generated by Django 6.0.2 on 2026-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appplan_app_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Format international: +237612345678', max_length=20),
        ),
    ]
