# Generated by Django 6.0.2 on 2026-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_ville_customuser_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appplan',
            name='app_key',
            field=models.CharField(choices=[('adgen', 'AdGen — Publicités IA'), ('resto', 'E-Shelle Resto'), ('rencontres', 'E-Shelle Love'), ('njangi', 'Njangi Digital'), ('edu', 'EduCam Pro'), ('allemand', 'E-Shelle Allemand (Ausbildung & Goethe)'), ('prep', 'Préparation Français (TEF/TCF)'), ('formations', 'Formations'), ('boutique', 'Boutique'), ('agro', 'E-Shelle Agro'), ('gaz', 'E-Shelle Gaz')], db_index=True, max_length=30),
        ),
    ]
