# Generated by Django 5.2.7 on 2025-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('dv_lottery', 'DV Lottery (Green Card)'), ('visa_france', 'Visa France'), ('visa_canada', 'Visa Canada'), ('visa_uk', 'Visa UK')], max_length=50)),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
