# Generated by Django 5.2.7 on 2025-10-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
