# Generated by Django 5.2.7 on 2025-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='photo',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='input/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('dv_lottery', 'DV Lottery (Green Card)'), ('visa_france', 'Visa France'), ('visa_uk', 'Visa UK'), ('visa_canada', 'Visa Canada')], max_length=32),
        ),
    ]
