# Generated by Django 6.0.7 on 2026-07-31 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salonhub_salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Téléphone du client')),
                ('date', models.DateField(verbose_name='Date du rendez-vous')),
                ('time', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('done', 'Terminé')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salonhub_salons.salon')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='salonhub_salons.service')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
