# Generated by Django 5.2.7 on 2026-01-14 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('job', "Offres d'emploi"), ('law', 'Loi & Immigration'), ('conference', 'Conférences & Événements'), ('opportunity', 'Opportunités'), ('advice', 'Conseils'), ('alert', 'Alertes')], max_length=20)),
                ('country_target', models.CharField(choices=[('US', 'USA'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('FR', 'France')], max_length=2)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(help_text='Résumé court (SEO + cartes)')),
                ('content', models.TextField(help_text='Article complet (texte long)')),
                ('featured_image', models.ImageField(blank=True, help_text='Image upload (recommandé en production)', null=True, upload_to='actualite/images/')),
                ('external_image_url', models.URLField(blank=True, help_text="Alternative si pas d'upload (ex: CDN)")),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo/MP4 URL (optionnel)')),
                ('external_link', models.URLField(blank=True, help_text='Source officielle (recommandé)')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='news_items', to='actualite.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['slug'], name='actualite_n_slug_025aa7_idx'), models.Index(fields=['category'], name='actualite_n_categor_b3e333_idx'), models.Index(fields=['country_target'], name='actualite_n_country_bdfc87_idx'), models.Index(fields=['-publish_date'], name='actualite_n_publish_247ef2_idx'), models.Index(fields=['is_published', '-publish_date'], name='actualite_n_is_publ_06a859_idx')],
            },
        ),
    ]
