# Generated by Django 5.2.7 on 2026-01-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='À la une'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['is_urgent', '-publish_date'], name='actualite_n_is_urge_c40973_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['is_important', '-publish_date'], name='actualite_n_is_impo_7fad73_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['-views_count'], name='actualite_n_views_c_3c7de0_idx'),
        ),
    ]
