# Generated by Django 5.0.6 on 2026-06-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated/images/')),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('backend', models.CharField(default='comfyui', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_image', to='scenes.scene')),
            ],
        ),
    ]
