# Generated by Django 5.2.7 on 2025-11-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom ou pseudo (optionnel)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (optionnel)')),
                ('pays_residence', models.CharField(max_length=100, verbose_name='Pays de résidence actuel')),
                ('pays_cibles', models.CharField(max_length=255, verbose_name='Pays ciblés (séparés par des virgules)')),
                ('domaine_metier', models.CharField(max_length=150, verbose_name='Métier / domaine')),
                ('niveau_etudes', models.CharField(choices=[('LT_BAC', '< Bac'), ('BAC', 'Bac'), ('BAC_PLUS_2_3', 'Bac+2/3'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat')], max_length=20, verbose_name="Niveau d'études")),
                ('annees_experience', models.PositiveIntegerField(verbose_name="Années d'expérience dans ce domaine")),
                ('niveau_anglais', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name="Niveau d'anglais")),
                ('niveau_langue_pays', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='Niveau dans la langue du pays ciblé')),
                ('budget', models.CharField(choices=[('INF_1000', '< 1000€'), ('1000_3000', '1000–3000€'), ('SUP_3000', '> 3000€')], max_length=20, verbose_name='Budget approximatif pour le projet')),
                ('horizon_depart', models.CharField(choices=[('LT_6', 'Moins de 6 mois'), ('6_12', '6–12 mois'), ('SUP_12', '> 12 mois')], max_length=20, verbose_name='Horizon de départ souhaité')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='VisaTravailApp.userprofile')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
