# Generated by Django 5.2.7 on 2025-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisaTravailApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100)),
                ('nom_programme', models.CharField(max_length=200)),
                ('profil_cible', models.TextField(help_text='Court texte expliquant pour qui est destiné ce visa.')),
                ('conditions_principales', models.TextField(help_text='Liste des conditions, séparées par des tirets ou des sauts de ligne.')),
                ('documents_cles', models.TextField(help_text='Liste des documents à préparer, séparés par des tirets ou des sauts de ligne.')),
                ('lien_officiel', models.URLField(max_length=500)),
                ('difficulte', models.CharField(choices=[('BAS', 'Bas'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], max_length=10)),
                ('delai_approx', models.CharField(max_length=50)),
                ('min_experience', models.PositiveIntegerField(default=0)),
                ('niveau_langue_min', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('niveau_etude_min', models.CharField(choices=[('LT_BAC', '< Bac'), ('BAC', 'Bac'), ('BAC_PLUS_2_3', 'Bac+2/3'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat')], default='LT_BAC', max_length=20)),
            ],
        ),
    ]
