# Generated by Django 5.2.7 on 2025-11-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisaTravailApp', '0002_visaoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_poste', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('entreprise', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('lien_offre', models.URLField(blank=True, max_length=500, verbose_name="Lien vers l'offre")),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='Source (site, contact…)')),
                ('statut', models.CharField(choices=[('A_POSTULER', 'À postuler'), ('ENVOYEE', 'Envoyée'), ('ENTRETIEN', 'Entretien'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='A_POSTULER', max_length=20, verbose_name='Statut')),
                ('date_candidature', models.DateField(blank=True, null=True, verbose_name='Date de candidature')),
                ('commentaire', models.TextField(blank=True, verbose_name='Notes / suivi')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='VisaTravailApp.userprofile')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
