# Generated by Django 5.2.7 on 2025-11-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisaTravailApp', '0003_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('entreprise', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('domaine', models.CharField(blank=True, max_length=150, verbose_name='Domaine / métier')),
                ('type_contrat', models.CharField(blank=True, choices=[('CDI', 'CDI / Permanent'), ('CDD', 'CDD / Temporaire'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance / Indépendant')], max_length=20, verbose_name='Type de contrat')),
                ('salaire', models.CharField(blank=True, max_length=100, verbose_name='Salaire / fourchette (optionnel)')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('exigences', models.TextField(blank=True, verbose_name='Exigences / profil recherché')),
                ('avantages', models.TextField(blank=True, verbose_name='Avantages (optionnel)')),
                ('lien_candidature', models.URLField(blank=True, max_length=500, verbose_name='Lien pour postuler (site officiel / job board)')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration (optionnel)")),
                ('est_active', models.BooleanField(default=True, verbose_name='Offre visible')),
                ('priorite', models.PositiveIntegerField(default=10, verbose_name='Niveau de priorité (1 = top)')),
            ],
            options={
                'ordering': ['priorite', '-date_publication'],
            },
        ),
    ]
