# Generated by Django 5.2.7 on 2026-02-13 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicJobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=60)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=220)),
                ('company', models.CharField(blank=True, max_length=220)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('description_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
