# Generated by Django 5.2.7 on 2026-02-13 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0002_publicjoboffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('key', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('content', models.TextField(help_text='Utilise {title}, {company}, {location}, {name}…')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='joblead',
            name='status',
            field=models.CharField(choices=[('found', 'Trouvée'), ('to_apply', 'À postuler'), ('applied', 'Postulée'), ('followup', 'Relance'), ('reply', 'Réponse')], db_index=True, default='found', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicjoboffer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='applicationpack',
            index=models.Index(fields=['user', 'updated_at'], name='job_agent_a_user_id_810a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='joblead',
            index=models.Index(fields=['user', 'status', 'created_at'], name='job_agent_j_user_id_367245_idx'),
        ),
        migrations.AddIndex(
            model_name='joblead',
            index=models.Index(fields=['user', 'match_score'], name='job_agent_j_user_id_cb69a7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobsearch',
            index=models.Index(fields=['user', 'created_at'], name='job_agent_j_user_id_d30ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='publicjoboffer',
            index=models.Index(fields=['is_active', 'created_at'], name='job_agent_p_is_acti_da6445_idx'),
        ),
        migrations.AddConstraint(
            model_name='joblead',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='uniq_joblead_user_url'),
        ),
        migrations.AddIndex(
            model_name='answertemplate',
            index=models.Index(fields=['language', 'key', 'is_active'], name='job_agent_a_languag_cd661e_idx'),
        ),
        migrations.AddIndex(
            model_name='lettertemplate',
            index=models.Index(fields=['language', 'is_active'], name='job_agent_l_languag_946426_idx'),
        ),
    ]
