# Generated by Django 5.2.7 on 2026-02-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0003_answertemplate_lettertemplate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicationpack',
            name='job_agent_a_user_id_810a9b_idx',
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='generated_email',
            field=models.TextField(blank=True),
        ),
    ]
