# Generated by Django 5.2.7 on 2026-02-13 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0004_remove_applicationpack_job_agent_a_user_id_810a9b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('subject', models.CharField(help_text='Ex: Relance — {title} ({company})', max_length=200)),
                ('content', models.TextField(help_text='Variables: {name} {title} {company} {location}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AddField(
            model_name='joblead',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblead',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='joblead',
            name='followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='applicationpack',
            index=models.Index(fields=['user', 'updated_at'], name='job_agent_a_user_id_810a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedocuments',
            index=models.Index(fields=['user', 'updated_at'], name='job_agent_c_user_id_ef032f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['user'], name='job_agent_c_user_id_16c0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='joblead',
            index=models.Index(fields=['user', 'applied_at'], name='job_agent_j_user_id_9f93fd_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptemplate',
            index=models.Index(fields=['language', 'is_active'], name='job_agent_f_languag_f6697d_idx'),
        ),
    ]
