# Generated by Django 6.0.2 on 2026-05-18 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=80)),
                ('quartier_ramassage', models.CharField(max_length=120)),
                ('quartier_livraison', models.CharField(max_length=120)),
                ('description_colis', models.CharField(max_length=220)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('CONTACTEE', 'Prestataire contacté'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de livraison',
                'verbose_name_plural': 'Demandes de livraisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
