# Generated by Django 5.2.7 on 2026-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('source_lang', models.CharField(blank=True, default='auto', max_length=10)),
                ('target_lang', models.CharField(blank=True, default='en', max_length=10)),
                ('original_file', models.FileField(upload_to='documents/translation/original/')),
                ('translated_file', models.FileField(blank=True, null=True, upload_to='documents/translation/translated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
