# Generated by Django 5.2.7 on 2025-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaTourismRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone / WhatsApp')),
                ('destination', models.CharField(choices=[('schengen', 'Espace Schengen (France, Belgique, Espagne, etc.)'), ('uk', 'Royaume-Uni'), ('usa', 'États-Unis'), ('canada', 'Canada'), ('autre', 'Autre pays')], max_length=20, verbose_name='Destination')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('pays_residence', models.CharField(max_length=100, verbose_name='Pays de résidence')),
                ('duree_sejour', models.CharField(choices=[('moins_15', 'Moins de 15 jours'), ('15_30', '15 à 30 jours'), ('30_90', '30 à 90 jours')], max_length=20, verbose_name='Durée du séjour')),
                ('objet_voyage', models.TextField(verbose_name='Objet du voyage')),
                ('a_un_emploi', models.BooleanField(default=False, verbose_name='A un emploi / activité pro')),
                ('a_invitation', models.BooleanField(default=False, verbose_name='A une lettre d’invitation')),
                ('a_deja_voyage', models.BooleanField(default=False, verbose_name='A déjà voyagé à l’étranger')),
                ('budget', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], max_length=10, verbose_name='Budget')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('score_chances', models.PositiveIntegerField(default=0, verbose_name='Score de chances (%)')),
                ('niveau_risque', models.CharField(default='À analyser', max_length=50, verbose_name='Niveau de risque')),
                ('points_forts', models.TextField(blank=True, verbose_name='Points forts')),
                ('points_faibles', models.TextField(blank=True, verbose_name='Points à renforcer')),
                ('documents', models.TextField(blank=True, verbose_name='Documents requis')),
                ('etapes', models.TextField(blank=True, verbose_name='Étapes clés')),
                ('remarques_destination', models.TextField(blank=True, verbose_name='Remarques destination')),
                ('conseils', models.TextField(blank=True, verbose_name='Conseils')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande Visa Tourisme',
                'verbose_name_plural': 'Demandes Visa Tourisme',
                'ordering': ['-created_at'],
            },
        ),
    ]
