# Generated by Django 5.2.7 on 2025-11-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisaTourismeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('solde', models.PositiveIntegerField(default=0, verbose_name='Crédits disponibles')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet de crédits Visa Tourisme',
                'verbose_name_plural': 'Wallets de crédits Visa Tourisme',
            },
        ),
    ]
