# Generated by Django 6.0.2 on 2026-05-23 20:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('plan_level', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro'), ('business', 'Business'), ('premium', 'Premium')], max_length=20)),
                ('monthly_price_xaf', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('included_boost_days', models.PositiveIntegerField(default=0)),
                ('included_ai_credits', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan prestataire',
                'verbose_name_plural': 'Plans prestataires',
                'ordering': ['order', 'monthly_price_xaf'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('resto', 'Resto'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('sante', 'Sante'), ('jobs', 'Jobs'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('agro', 'Agro'), ('immobilier', 'Immobilier'), ('quincaillerie', 'Quincaillerie'), ('general', 'General')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro'), ('business', 'Business'), ('premium', 'Premium')], db_index=True, default='free', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('boost_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ai_credits', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0)),
                ('phone_clicks', models.PositiveIntegerField(default=0)),
                ('detail_clicks', models.PositiveIntegerField(default=0)),
                ('leads_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil business',
                'verbose_name_plural': 'Profils business',
                'ordering': ['-boost_expires_at', '-subscription_expires_at', '-leads_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('view', 'Vue'), ('whatsapp', 'WhatsApp'), ('phone', 'Appel'), ('detail', 'Details'), ('order', 'Commande')], db_index=True, max_length=20)),
                ('source', models.CharField(default='chat', max_length=40)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_events', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Demande/clic business',
                'verbose_name_plural': 'Demandes/clics business',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoostCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('amount_xaf', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Boost prestataire',
                'verbose_name_plural': 'Boosts prestataires',
                'ordering': ['-ends_at'],
            },
        ),
        migrations.CreateModel(
            name='AICreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_movements', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Mouvement credit IA',
                'verbose_name_plural': 'Mouvements credits IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['module', 'plan', 'is_active'], name='business_bu_module_0dc666_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['content_type', 'object_id'], name='business_bu_content_1ee791_idx'),
        ),
    ]
