# Generated by Django 6.0.2 on 2026-05-24 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash_on_delivery', 'Paiement a la reception'), ('momo_manual', 'Mobile Money manuel'), ('access_code', "Code d'acces"), ('online', 'Paiement en ligne')], default='cash_on_delivery', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirme'), ('canceled', 'Annule')], default='pending', max_length=20)),
                ('amount_xaf', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='business.businessprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='business.providerplan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de paiement prestataire',
                'verbose_name_plural': 'Demandes de paiement prestataire',
                'ordering': ['-created_at'],
            },
        ),
    ]
