# Generated by Django 6.0.2 on 2026-05-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_homeadslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeadslide',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeadslide',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
