# Generated by Django 6.0.2 on 2026-05-27 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_homeadslide_clicks_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSectorCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('module', models.CharField(choices=[('resto', 'Resto'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('sante', 'Sante'), ('jobs', 'Jobs'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('agro', 'Agro'), ('immobilier', 'Immobilier'), ('quincaillerie', 'Quincaillerie'), ('general', 'General')], db_index=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('goal', models.CharField(blank=True, help_text='Ex: recruter 20 restos Premium a Douala', max_length=180)),
                ('pitch', models.TextField(blank=True, help_text='Script commercial ou message WhatsApp de campagne.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('target_businesses', models.PositiveIntegerField(default=0)),
                ('budget_xaf', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('done', 'Terminee')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagne secteur premium',
                'verbose_name_plural': 'Campagnes secteurs premium',
                'ordering': ['-starts_at', 'name'],
            },
        ),
    ]
