# Generated by Django 6.0.2 on 2026-05-29 11:28

from django.db import migrations, models
from django.utils.text import slugify


def populate_public_slugs(apps, schema_editor):
    BusinessProfile = apps.get_model("business", "BusinessProfile")
    aliases = {
        "sante_pro": "sante",
        "sante_product": "sante",
        "annonces": "market",
        "tibo": "boutique",
    }
    used = set(
        BusinessProfile.objects.exclude(public_slug__isnull=True)
        .exclude(public_slug="")
        .values_list("public_slug", flat=True)
    )
    for profile in BusinessProfile.objects.order_by("id"):
        changed = []
        if profile.module in aliases:
            profile.module = aliases[profile.module]
            changed.append("module")
        if not profile.public_slug:
            base = slugify(profile.slug or f"{profile.name}-{profile.city}" or profile.name)[:210] or "business"
            slug = base
            n = 1
            while slug in used:
                slug = f"{base}-{n}"[:240]
                n += 1
            used.add(slug)
            profile.public_slug = slug
            changed.append("public_slug")
        if changed:
            profile.save(update_fields=changed)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_premiumsectorcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='Slug public stable pour la vitrine E-Shelle, ex: /business/@ma-boutique/.', max_length=240, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_slugs, noop_reverse),
        migrations.AlterField(
            model_name='businessprofile',
            name='module',
            field=models.CharField(choices=[('resto', 'Resto'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('sante', 'Sante'), ('pharma', 'Pharma'), ('jobs', 'Jobs'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('market', 'Market'), ('agro', 'Agro'), ('immobilier', 'Immobilier'), ('auto', 'Auto'), ('transport', 'Transport'), ('njangi', 'Njangi'), ('adgen', 'AdGen'), ('edu', 'EduCam Pro'), ('quincaillerie', 'Quincaillerie'), ('general', 'General')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='premiumsectorcampaign',
            name='module',
            field=models.CharField(choices=[('resto', 'Resto'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('sante', 'Sante'), ('pharma', 'Pharma'), ('jobs', 'Jobs'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('market', 'Market'), ('agro', 'Agro'), ('immobilier', 'Immobilier'), ('auto', 'Auto'), ('transport', 'Transport'), ('njangi', 'Njangi'), ('adgen', 'AdGen'), ('edu', 'EduCam Pro'), ('quincaillerie', 'Quincaillerie'), ('general', 'General')], db_index=True, max_length=30),
        ),
    ]
