# Generated by Django 6.0.2 on 2026-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businessprofile_public_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='module',
            field=models.CharField(choices=[('resto', 'Resto'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('sante', 'Sante'), ('pharma', 'Pharma'), ('jobs', 'Jobs'), ('services', 'Services'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('market', 'Market'), ('agro', 'Agro'), ('immobilier', 'Immobilier'), ('auto', 'Auto'), ('transport', 'Transport'), ('njangi', 'Njangi'), ('adgen', 'AdGen'), ('edu', 'EduCam Pro'), ('quincaillerie', 'Quincaillerie'), ('general', 'General')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='premiumsectorcampaign',
            name='module',
            field=models.CharField(choices=[('resto', 'Resto'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('sante', 'Sante'), ('pharma', 'Pharma'), ('jobs', 'Jobs'), ('services', 'Services'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('market', 'Market'), ('agro', 'Agro'), ('immobilier', 'Immobilier'), ('auto', 'Auto'), ('transport', 'Transport'), ('njangi', 'Njangi'), ('adgen', 'AdGen'), ('edu', 'EduCam Pro'), ('quincaillerie', 'Quincaillerie'), ('general', 'General')], db_index=True, max_length=30),
        ),
    ]
