# Generated by Django 6.0.2 on 2026-05-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_businessprofile_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKeyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Gratuit'), ('key', 'Business Key'), ('pro', 'Ambassadeur Pro')], db_index=True, default='free', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_key_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte Business Key',
                'verbose_name_plural': 'Comptes Business Key',
            },
        ),
        migrations.CreateModel(
            name='BusinessKeyPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Gratuit'), ('key', 'Business Key'), ('pro', 'Ambassadeur Pro')], db_index=True, max_length=20)),
                ('amount_xaf', models.PositiveIntegerField(default=0)),
                ('momo_number', models.CharField(blank=True, max_length=40)),
                ('proof', models.FileField(blank=True, null=True, upload_to='business_key/proofs/')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirme'), ('canceled', 'Annule')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_key_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement Business Key',
                'verbose_name_plural': 'Paiements Business Key',
                'ordering': ['-created_at'],
            },
        ),
    ]
