# Generated by Django 6.0.2 on 2026-06-01 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_businesskeyaccount_businesskeypaymentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('sector', models.CharField(choices=[('restaurant', 'Restaurant'), ('pressing', 'Pressing'), ('gaz', 'Gaz'), ('immobilier', 'Immobilier'), ('auto', 'Auto'), ('agro', 'Agro'), ('market', 'Market'), ('sante', 'Sante'), ('services', 'Services'), ('other', 'Autre')], db_index=True, default='other', max_length=30)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacte'), ('interested', 'Interesse'), ('follow_up', 'A relancer'), ('converted', 'Converti'), ('refused', 'Refuse')], db_index=True, default='new', max_length=30)),
                ('potential_xaf', models.PositiveIntegerField(default=15000)),
                ('next_follow_up_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_key_crm_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospect CRM partenaire',
                'verbose_name_plural': 'Prospects CRM partenaires',
                'ordering': ['status', 'next_follow_up_at', '-updated_at'],
                'indexes': [models.Index(fields=['partner', 'status'], name='business_pa_partner_fd4342_idx'), models.Index(fields=['partner', 'sector'], name='business_pa_partner_537c1d_idx')],
            },
        ),
    ]
