# Generated by Django 6.0.2 on 2026-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_partnercrmlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('marketplace', 'Marketplace'), ('love', 'E-Shelle Love'), ('formations', 'Formations'), ('njangi', 'Njangi Tontine'), ('agro', 'Agro B2B/B2C'), ('pharma', 'Pharma'), ('transport', 'Transport'), ('tchaslucpay', 'Tchaslucpay'), ('pressing', 'Pressing'), ('resto', 'Resto'), ('immobilier', 'Immobilier'), ('auto', 'Auto'), ('gaz', 'Gaz & Livraison'), ('jobs', 'Jobs'), ('adgen', 'AdGen'), ('edu', 'EduCam Pro'), ('sante', 'Sante'), ('simplo', 'Simplo'), ('market', 'Market general'), ('services_web', 'Services Web')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='% commission sur vente', max_digits=5)),
                ('commission_fixe', models.DecimalField(decimal_places=0, default=0, help_text='Commission fixe en FCFA', max_digits=10)),
                ('is_recurring', models.BooleanField(default=False, help_text='Commission mensuelle recurrente')),
                ('is_active', models.BooleanField(default=True)),
                ('script_vente', models.TextField(blank=True, help_text='Script WhatsApp pour vendre cette app')),
                ('priority', models.IntegerField(default=0, help_text="Ordre d'affichage (0=premier)")),
                ('icon', models.CharField(blank=True, help_text='Icone ou emoji simple', max_length=50)),
            ],
            options={
                'verbose_name': 'Commission par App',
                'verbose_name_plural': 'Commissions par App',
                'ordering': ['priority', 'app_name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('gratuit', 'Gratuit'), ('business_key', 'Business Key'), ('ambassadeur', 'Ambassadeur Pro'), ('multi_app', 'Multi-App Master')], max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('prix_fcfa', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('bonus_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apps_accessibles', models.ManyToManyField(blank=True, help_text='Apps dont le partenaire peut vendre et toucher commission', to='business.appcommission')),
            ],
            options={
                'verbose_name': 'Niveau Partenaire',
                'verbose_name_plural': 'Niveaux Partenaires',
            },
        ),
    ]
