# Generated by Django 6.0.2 on 2026-06-01 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_appcommission_partnerlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Produit'), ('service', 'Service'), ('menu', 'Menu'), ('delivery', 'Livraison'), ('offer', 'Offre')], default='product', max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('price_label', models.CharField(blank=True, help_text='Ex: 2 500 FCFA, Prix a discuter.', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business/catalogue/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Produit/service business',
                'verbose_name_plural': 'Produits/services business',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['business', 'is_active', 'order'], name='business_bu_busines_5de10c_idx')],
            },
        ),
    ]
