# Generated by Django 6.0.2 on 2026-06-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_businesscatalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='activation_status',
            field=models.CharField(choices=[('demo', 'Demo'), ('pending', 'Paiement en attente'), ('active', 'Activee')], db_index=True, default='demo', max_length=20),
        ),
    ]
