# Generated by Django 6.0.2 on 2026-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businessprofile_activation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeadslide',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image / flyer'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='homeadslide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='business/home-slides/videos/'),
        ),
        migrations.AddField(
            model_name='homeadslide',
            name='video_url',
            field=models.URLField(blank=True, help_text="Lien direct MP4 optionnel si la video n'est pas uploadee."),
        ),
    ]
