# Generated by Django 6.0.2 on 2026-06-03 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_homeadslide_media_type_homeadslide_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAIKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Pret a vendre'), ('delivered', 'Livre'), ('archived', 'Archive')], db_index=True, default='draft', max_length=20)),
                ('client_brief', models.JSONField(blank=True, default=dict)),
                ('recommended_agents', models.JSONField(blank=True, default=list)),
                ('chatbot_prompt', models.TextField(blank=True)),
                ('website_plan', models.JSONField(blank=True, default=dict)),
                ('content_pack', models.JSONField(blank=True, default=dict)),
                ('whatsapp_scripts', models.JSONField(blank=True, default=list)),
                ('seo_plan', models.JSONField(blank=True, default=dict)),
                ('video_plan', models.JSONField(blank=True, default=dict)),
                ('automation_plan', models.JSONField(blank=True, default=list)),
                ('qa_checklist', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_delivery_kit', to='business.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_ai_kits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kit client IA',
                'verbose_name_plural': 'Kits clients IA',
                'ordering': ['-updated_at'],
            },
        ),
    ]
