# Generated by Django 6.0.2 on 2026-06-03 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_clientaikit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmetSearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=260)),
                ('module', models.CharField(choices=[('resto', 'Resto'), ('gaz', 'Gaz'), ('pressing', 'Pressing'), ('sante', 'Sante'), ('pharma', 'Pharma'), ('jobs', 'Jobs'), ('services', 'Services'), ('formation', 'Formation'), ('boutique', 'Boutique'), ('market', 'Market'), ('agro', 'Agro'), ('immobilier', 'Immobilier'), ('auto', 'Auto'), ('transport', 'Transport'), ('njangi', 'Njangi'), ('adgen', 'AdGen'), ('edu', 'EduCam Pro'), ('quincaillerie', 'Quincaillerie'), ('general', 'General')], db_index=True, default='general', max_length=30)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('consent_share_contact', models.BooleanField(default=False)),
                ('consent_promotions', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('notified', 'Prestataires notifies'), ('in_progress', 'En traitement'), ('satisfied', 'Satisfaite'), ('expired', 'Expiree'), ('canceled', 'Annulee')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(default='search', max_length=40)),
                ('notified_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmet_search_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande non satisfaite',
                'verbose_name_plural': 'Demandes non satisfaites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmetSearchResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('contacted', 'Client contacte'), ('not_available', 'Non disponible'), ('satisfied', 'Client satisfait')], default='contacted', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmet_search_responses', to='business.businessprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='business.unmetsearchrequest')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmet_search_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reponse a une demande non satisfaite',
                'verbose_name_plural': 'Reponses aux demandes non satisfaites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unmetsearchrequest',
            index=models.Index(fields=['module', 'city', 'status'], name='business_un_module_8741a6_idx'),
        ),
        migrations.AddIndex(
            model_name='unmetsearchrequest',
            index=models.Index(fields=['created_at', 'status'], name='business_un_created_37d545_idx'),
        ),
        migrations.AddConstraint(
            model_name='unmetsearchresponse',
            constraint=models.UniqueConstraint(fields=('request', 'business'), name='uniq_unmet_response_per_business'),
        ),
    ]
