# Generated by Django 6.0.2 on 2026-06-03 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_unmetsearchrequest_unmetsearchresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unmetsearchrequest',
            name='ai_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='unmetsearchrequest',
            name='ai_priority',
            field=models.CharField(db_index=True, default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='unmetsearchrequest',
            name='assigned_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_unmet_search_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unmetsearchrequest',
            name='conversion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unmetsearchrequest',
            name='estimated_value_xaf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unmetsearchrequest',
            name='lead_score',
            field=models.PositiveIntegerField(db_index=True, default=50),
        ),
        migrations.AlterField(
            model_name='unmetsearchrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('viewed', 'Vue'), ('notified', 'Prestataires notifies'), ('in_progress', 'En traitement'), ('contacted', 'Client contacte'), ('provider_found', 'Prestataire trouve'), ('sold', 'Vendu'), ('lost', 'Perdu'), ('satisfied', 'Satisfaite'), ('expired', 'Expiree'), ('canceled', 'Annulee')], db_index=True, default='new', max_length=20),
        ),
    ]
