# Generated by Django 6.0.2 on 2026-06-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_unmetsearchrequest_ai_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo officiel du business.', null=True, upload_to='business/logos/'),
        ),
        migrations.CreateModel(
            name='BusinessCatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business/catalogue/extra/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='business.businesscatalogitem')),
            ],
            options={
                'verbose_name': 'Photo produit supplementaire',
                'verbose_name_plural': 'Photos produit supplementaires',
            },
        ),
    ]
