# Generated by Django 6.0.2 on 2026-06-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_businessprofile_logo_businesscatalogitemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nom du site / Titre')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre / Tagline')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='Badge / Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business/presentation-slides/', verbose_name='Capture / Maquette')),
                ('mockup_type', models.CharField(choices=[('desktop', 'Navigateur Desktop'), ('laptop', 'MacBook Laptop'), ('mobile', 'Smartphone Mobile'), ('glass', 'Carte Glassmorphism')], default='desktop', max_length=20, verbose_name='Type de Maquette')),
                ('cta_label', models.CharField(default='Visiter le site', max_length=50, verbose_name='Texte du bouton')),
                ('cta_url', models.CharField(blank=True, max_length=250, verbose_name='URL du bouton')),
                ('tech_stack', models.CharField(blank=True, help_text='Ex: Django, Postgres, TailwindCSS', max_length=200, verbose_name='Technologies (séparées par des virgules)')),
                ('features', models.TextField(blank=True, help_text='Ex: Paiement Mobile Money\nAlertes temps réel', verbose_name='Fonctionnalités clés (une par ligne)')),
                ('bg_gradient', models.CharField(blank=True, default='linear-gradient(135deg, #0f172a, #1e293b)', help_text='Style linear-gradient CSS complet.', max_length=250, verbose_name='Gradient de fond CSS')),
                ('text_color', models.CharField(default='#ffffff', max_length=30, verbose_name='Couleur du texte (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide de Présentation (Maquette)',
                'verbose_name_plural': 'Slides de Présentation (Maquettes)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
