# Generated by Django 6.0.2 on 2026-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_presentationslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPromotionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre descriptif (admin)')),
                ('image', models.ImageField(upload_to='business/promo-slides/', verbose_name='Affiche Canva')),
                ('cta_url', models.CharField(blank=True, max_length=250, verbose_name="Lien de l'application (optionnel)")),
                ('cta_label', models.CharField(blank=True, default="Accéder à l'application", max_length=100, verbose_name="Texte du bouton sous l'affiche (optionnel)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide de promotion E-Shelle',
                'verbose_name_plural': 'Slides de promotion E-Shelle',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
