# Generated by Django 6.0.2 on 2026-07-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_apppromotionslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscatalogitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date de peremption.', null=True),
        ),
        migrations.AddField(
            model_name='businesscatalogitem',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Numero de lot.', max_length=100),
        ),
        migrations.AddField(
            model_name='businesscatalogitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantite en stock (laisser vide si non suivi).', null=True),
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note de 1 a 5.')),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Decoche pour masquer cet avis de la fiche publique.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.businessprofile')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
