# Generated by Django 6.0.2 on 2026-07-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_businesscatalogitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscatalogitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='businesscatalogitem',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='businesscatalogitem',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de fois que ce produit/service precis a ete consulte.'),
        ),
    ]
