# Generated by Django 6.0.2 on 2026-07-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_remove_businesscatalogitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscatalogitem',
            name='lot_number',
        ),
    ]
