# Generated by Django 6.0.2 on 2026-07-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_remove_businesscatalogitem_lot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaikit',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Prêt à vendre'), ('delivered', 'Livré'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20),
        ),
    ]
