# Generated by Django 6.0.2 on 2026-07-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_businessactivationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='expiry_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Essai Business gratuit de 7 jours en cours (pas un vrai paiement).'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Badge Vérifié — active automatiquement au premier paiement confirme.'),
        ),
    ]
