# Generated by Django 6.0.2 on 2026-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_businessprofile_expiry_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscatalogitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien de la vidéo (Cloudinary, YouTube, TikTok...)', max_length=500, null=True),
        ),
    ]
