# Generated by Django 6.0.2 on 2026-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_businesscatalogitem_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(upload_to='business/partners/', verbose_name='Logo du partenaire')),
                ('website_url', models.URLField(blank=True, max_length=250, verbose_name='Lien du site (optionnel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire E-Shelle',
                'verbose_name_plural': 'Partenaires E-Shelle',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
