# Generated by Django 6.0.2 on 2026-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_partnerlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='country',
            field=models.CharField(blank=True, default='Cameroun', max_length=100),
        ),
    ]
