# Generated by Django 6.0.2 on 2026-07-14 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_canadajoboffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaCVEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Ex: Baccalauréat en génie logiciel (équivalent Licence)', max_length=200)),
                ('school', models.CharField(help_text="Nom de l'établissement", max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('province_country', models.CharField(default='Cameroun', help_text='Province ou Pays', max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, help_text='Laisser vide si en cours', null=True)),
                ('description', models.TextField(blank=True, help_text='Détails optionnels sur le parcours académique')),
                ('order', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_cv_educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation Canada',
                'verbose_name_plural': 'Formations Canada',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='CanadaCVExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Développeur Python', max_length=200)),
                ('company', models.CharField(help_text="Nom de l'employeur", max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('province_country', models.CharField(default='Cameroun', help_text='Province ou Pays', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Laisser vide si en cours', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text="Responsabilités et réalisations clés. Utilisez des verbes d'action et chiffrez vos résultats.")),
                ('order', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_cv_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expérience Canada',
                'verbose_name_plural': 'Expériences Canada',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CanadaCVLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Ex: Français, Anglais', max_length=50)),
                ('proficiency', models.CharField(choices=[('Maternelle', 'Langue maternelle / Native'), ('Avancé', 'Avancé (C1/C2)'), ('Intermédiaire', 'Intermédiaire (B1/B2)'), ('Débutant', 'Débutant (A1/A2)')], max_length=30)),
                ('certificate', models.CharField(blank=True, help_text='Ex: TEF Canada CLB 9, IELTS 7.5', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_cv_languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Langue Canada',
                'verbose_name_plural': 'Langues Canada',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='CanadaCVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, help_text='Ville, Pays actuel (ex: Douala, Cameroun)', max_length=300)),
                ('linkedin', models.URLField(blank=True, help_text='Lien vers votre profil LinkedIn')),
                ('target_sector', models.CharField(blank=True, help_text="Secteur d'activité visé (ex: Informatique, Santé, Construction)", max_length=100)),
                ('target_provinces', models.CharField(blank=True, help_text='Provinces acceptées au Canada (ex: Québec, Ontario, Alberta)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canada_cv_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil CV Canada',
                'verbose_name_plural': 'Profils CV Canada',
            },
        ),
        migrations.CreateModel(
            name='GeneratedCanadaResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_offer_title', models.CharField(blank=True, max_length=300)),
                ('custom_offer_company', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=5)),
                ('content_html', models.TextField(help_text='Contenu HTML du CV généré')),
                ('ai_cover_letter', models.TextField(blank=True, help_text='Lettre de motivation générée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canada_resumes', to='jobs.canadajoboffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_resumes_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Canada généré',
                'verbose_name_plural': 'Documents Canada générés',
                'ordering': ['-created_at'],
            },
        ),
    ]
