# Generated by Django 6.0.2 on 2026-07-14 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canada_resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaImmigrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=25)),
                ('education_level', models.CharField(choices=[('doctorate', 'Doctorat / Doctorate (PhD)'), ('master', "Maîtrise / Master's degree"), ('two_degrees', 'Deux diplômes ou plus (dont un de 3 ans) / Two or more degrees'), ('bachelor', "Baccalauréat (3 ans et +) / Bachelor's degree (3+ years)"), ('two_year', 'Diplôme de 2 ans / Two-year program'), ('one_year', 'Diplôme de 1 an / One-year program'), ('high_school', 'Études secondaires / High school')], default='bachelor', max_length=50)),
                ('work_experience_years', models.IntegerField(default=3)),
                ('tcf_level', models.CharField(choices=[('C2', 'C2 (CLB 10+)'), ('C1', 'C1 (CLB 9)'), ('B2', 'B2 (CLB 7-8)'), ('B1', 'B1 (CLB 5-6)'), ('A2', 'A2 (CLB 4)'), ('A1', 'A1 (CLB 1-3)')], default='B2', max_length=10)),
                ('has_lmia_job', models.BooleanField(default=False)),
                ('crs_score', models.IntegerField(default=0)),
                ('ai_roadmap', models.TextField(blank=True, help_text="Feuille de route générée par l'IA")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canada_immigration_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Profil d'immigration Canada",
                'verbose_name_plural': "Profils d'immigration Canada",
            },
        ),
    ]
