# Generated by Django 6.0.2 on 2026-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canada_resume', '0002_canadaimmigrationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcanadaresume',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('bi', 'Bilingue')], default='fr', max_length=5),
        ),
    ]
