# Generated by Django 6.0.2 on 2026-08-08 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canada_resume', '0003_alter_generatedcanadaresume_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaCVProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du projet ou de la réalisation', max_length=200)),
                ('description', models.TextField(help_text='Description de la réalisation, objectifs et résultats obtenus')),
                ('project_url', models.URLField(blank=True, help_text='Lien vers la réalisation (site web, démo, GitHub)')),
                ('image', models.ImageField(blank=True, help_text="Photo ou capture d'écran de la réalisation", null=True, upload_to='canada/portfolio/')),
                ('video_url', models.URLField(blank=True, help_text='Lien vidéo (YouTube, Vimeo, etc.) de présentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_cv_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réalisation / Projet',
                'verbose_name_plural': 'Réalisations / Projets',
            },
        ),
    ]
