# Generated by Django 6.0.2 on 2026-08-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canada_resume', '0004_canadacvproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description / Résumé')),
                ('resource_type', models.CharField(choices=[('pdf', 'Guide PDF'), ('video', 'Tutoriel Vidéo'), ('excel', 'Fichier Excel'), ('other', 'Autre Ressource')], default='pdf', max_length=20, verbose_name='Type de ressource')),
                ('file', models.FileField(blank=True, null=True, upload_to='canada/resources/', verbose_name='Fichier joint (PDF, Excel...)')),
                ('video_url', models.URLField(blank=True, verbose_name='Lien URL de la vidéo (YouTube, Vimeo, etc.)')),
                ('is_premium', models.BooleanField(default=True, verbose_name='Contenu payant (Premium uniquement)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements / vues')),
            ],
            options={
                'verbose_name': 'Ressource Canada',
                'verbose_name_plural': 'Ressources Canada',
                'ordering': ['-created_at'],
            },
        ),
    ]
