# Generated by Django 6.0.2 on 2026-09-20 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canada_resume', '0005_canadaresource'),
        ('preparation_tests', '0030_competencytag_courseexercise_competency_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('language', 'Préparer mon test de français'), ('work', 'Travailler au Canada'), ('study', 'Étudier au Canada'), ('settle', 'Préparer mon installation'), ('visit', 'Visiter le Canada')], default='language', max_length=12)),
                ('exam', models.CharField(choices=[('tcf', 'TCF Canada'), ('tef', 'TEF Canada')], default='tcf', max_length=3)),
                ('working_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A2', max_length=2)),
                ('target_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B2', max_length=2)),
                ('daily_minutes', models.PositiveSmallIntegerField(choices=[(10, '10 minutes'), (20, '20 minutes'), (30, '30 minutes'), (45, '45 minutes')], default=20)),
                ('assessment', models.JSONField(blank=True, default=dict)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immigration_journey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImmigrationAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='imm97_user_day_usage')],
            },
        ),
        migrations.CreateModel(
            name='LearningDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.courseexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise'), name='imm97_user_exercise_draft')],
            },
        ),
    ]
