# Generated by Django 5.0.6 on 2026-06-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='generated/audio/')),
                ('backend', models.CharField(default='coqui', max_length=80)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_over', to='scenes.scene')),
            ],
        ),
    ]
