# Generated by Django 5.2.7 on 2025-11-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('canada', 'Canada'), ('australia', 'Australie')], default='canada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, help_text='Ex : Baccalauréat, Licence, Master, Doctorat...', max_length=255)),
                ('french_level', models.CharField(blank=True, help_text='Ex : B1, B2, C1, TEF Canada, TCF Canada...', max_length=255)),
                ('english_level', models.CharField(blank=True, help_text='Ex : IELTS 6.5, 7.0, PTE, TOEFL...', max_length=255)),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text="Nombre d'années d'expérience à temps plein dans ton domaine principal.", null=True)),
                ('profession_title', models.CharField(blank=True, help_text='Intitulé de ton poste principal.', max_length=255)),
                ('noc_code', models.CharField(blank=True, help_text='Code NOC/TEER (Canada), si connu.', max_length=20)),
                ('anzsco_code', models.CharField(blank=True, help_text='Code ANZSCO (Australie), si connu.', max_length=20)),
                ('has_family_in_country', models.BooleanField(default=False, help_text='As-tu de la famille proche dans le pays visé ?')),
                ('has_job_offer', models.BooleanField(default=False, help_text="As-tu une offre d'emploi dans le pays visé ?")),
                ('notes', models.TextField(blank=True, help_text='Infos complémentaires (séjours précédents, études dans le pays, etc.).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PRPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Terminé')], default='todo', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='permanent_residence.prprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PRResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(default='video', help_text='Ex : video, capture, article, checklist...', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='permanent_residence.prprofile')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='permanent_residence.prplanstep')),
            ],
        ),
    ]
