# Generated by Django 5.2.7 on 2025-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permanent_residence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prplanstep',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='prprofile',
            name='english_exam',
            field=models.CharField(choices=[('none', 'Aucun test pour l’instant'), ('ielts_general', 'IELTS General Training'), ('celpip_general', 'CELPIP General'), ('pte_core', 'PTE Core'), ('toefl', 'TOEFL iBT (info seulement)')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='french_exam',
            field=models.CharField(choices=[('none', 'Aucun test pour l’instant'), ('tef_canada', 'TEF Canada'), ('tcf_canada', 'TCF Canada'), ('tefaq', 'TEFAQ'), ('tcf_other', 'TCF autre / DELF / DALF')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='prplanstep',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prplanstep',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='anzsco_code',
            field=models.CharField(blank=True, help_text='Code ANZSCO si tu le connais (Australie).', max_length=20),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('AU', 'Australie')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Secondaire / Bac'), ('post_1_2', 'Post-secondaire 1–2 ans (BTS, DUT, etc.)'), ('bachelor', 'Licence / Bachelor'), ('master', 'Master'), ('phd', 'Doctorat / PhD'), ('other', 'Autre / mixte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='english_level',
            field=models.CharField(choices=[('none', 'Je ne parle pas / presque pas'), ('a2', 'A1–A2 (débutant)'), ('b1', 'B1 (intermédiaire)'), ('b2', 'B2 (intermédiaire avancé)'), ('c1', 'C1 (avancé)'), ('c2', 'C2 (très avancé)')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='french_level',
            field=models.CharField(choices=[('none', 'Je ne parle pas / presque pas'), ('a2', 'A1–A2 (débutant)'), ('b1', 'B1 (intermédiaire)'), ('b2', 'B2 (intermédiaire avancé)'), ('c1', 'C1 (avancé)'), ('c2', 'C2 (très avancé)')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='has_family_in_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='has_job_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='noc_code',
            field=models.CharField(blank=True, help_text='Code NOC / TEER si tu le connais (Canada).', max_length=20),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='profession_title',
            field=models.CharField(blank=True, help_text='Intitulé principal de ton poste (ex: Développeur logiciel, Infirmier…).', max_length=200),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre d’années d’expérience à temps plein dans un métier qualifié.', null=True),
        ),
        migrations.DeleteModel(
            name='PRResource',
        ),
    ]
