# Generated by Django 5.2.7 on 2025-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permanent_residence', '0002_alter_prplanstep_options_prprofile_english_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prprofile',
            name='english_ce',
            field=models.CharField(blank=True, max_length=20, verbose_name='Anglais – Compréhension écrite (Reading)'),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='english_co',
            field=models.CharField(blank=True, help_text='Ex : 6.5, 7.0, CLB 8 …', max_length=20, verbose_name='Anglais – Compréhension orale (Listening)'),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='english_ee',
            field=models.CharField(blank=True, max_length=20, verbose_name='Anglais – Expression écrite (Writing)'),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='english_eo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Anglais – Expression orale (Speaking)'),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='french_ce',
            field=models.CharField(blank=True, help_text='Ex : 280/300, CLB 8, B2 …', max_length=20, verbose_name='Français – Compréhension écrite (CE)'),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='french_co',
            field=models.CharField(blank=True, help_text='Ex : 310/360, CLB 7, B2 …', max_length=20, verbose_name='Français – Compréhension orale (CO)'),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='french_ee',
            field=models.CharField(blank=True, max_length=20, verbose_name='Français – Expression écrite (EE)'),
        ),
        migrations.AddField(
            model_name='prprofile',
            name='french_eo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Français – Expression orale (EO)'),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='anzsco_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='english_exam',
            field=models.CharField(choices=[('none', 'Aucun test pour l’instant'), ('ielts_general', 'IELTS General Training'), ('celpip_general', 'CELPIP General'), ('pte_core', 'PTE Core'), ('toefl', 'TOEFL iBT (info)')], default='none', max_length=30, verbose_name='Test d’anglais'),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='english_level',
            field=models.CharField(choices=[('none', 'Pas encore de niveau ou test'), ('a2', 'A1–A2 (débutant)'), ('b1', 'B1 (intermédiaire)'), ('b2', 'B2 (intermédiaire avancé)'), ('c1', 'C1 (avancé)'), ('c2', 'C2 (très avancé)')], default='none', max_length=10, verbose_name='Niveau global d’anglais'),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='french_exam',
            field=models.CharField(choices=[('none', 'Aucun test pour l’instant'), ('tef_canada', 'TEF Canada'), ('tcf_canada', 'TCF Canada'), ('tefaq', 'TEFAQ'), ('tcf_other', 'TCF / DELF / DALF (autre)')], default='none', max_length=30, verbose_name='Test de français'),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='french_level',
            field=models.CharField(choices=[('none', 'Pas encore de niveau ou test'), ('a2', 'A1–A2 (débutant)'), ('b1', 'B1 (intermédiaire)'), ('b2', 'B2 (intermédiaire avancé)'), ('c1', 'C1 (avancé)'), ('c2', 'C2 (très avancé)')], default='none', max_length=10, verbose_name='Niveau global de français'),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='noc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='profession_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text="Années d'expérience qualifiée à temps plein.", null=True),
        ),
    ]
