# Generated by Django 5.2.7 on 2025-11-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permanent_residence', '0003_prprofile_english_ce_prprofile_english_co_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identifiant dans l’URL, ex: 'entree-express' ou 'nsw-skilled-visa'.", unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('AU', 'Australie')], max_length=2)),
                ('category', models.CharField(blank=True, help_text='Ex: Entrée Express, PNP, Visa Skilled, State Nomination…', max_length=80)),
                ('short_label', models.CharField(blank=True, help_text="Label court pour les badges, ex: 'Entrée Express – FSW'.", max_length=80)),
                ('summary', models.TextField(blank=True, help_text='Résumé rapide du programme (objectif, profil ciblé).')),
                ('official_url', models.URLField(blank=True, help_text='Lien officiel vers le site du gouvernement.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Programme d'immigration",
                'verbose_name_plural': "Programmes d'immigration",
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('OFFICIAL', 'Lien officiel'), ('VIDEO', 'Vidéo'), ('SCREENSHOT', 'Capture d’écran'), ('DOC', 'Document / PDF'), ('CHECKLIST', 'Checklist'), ('ARTICLE', 'Article / Guide'), ('OTHER', 'Autre')], default='ARTICLE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rp_resources/screenshots/')),
                ('embed_code', models.TextField(blank=True, help_text='Optionnel: code d’intégration (iframe) pour une vidéo.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Permet de trier l’ordre d’affichage des ressources.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='permanent_residence.immigrationprogram')),
            ],
            options={
                'verbose_name': 'Ressource programme RP',
                'verbose_name_plural': 'Ressources programme RP',
                'ordering': ['resource_type', 'order', 'id'],
            },
        ),
    ]
