# Generated by Django 6.0.2 on 2026-10-02 08:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Prestation')),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de base indicatif')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service de prestation',
                'verbose_name_plural': 'Services de prestation',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('F', 'Femme'), ('M', 'Homme')], max_length=5, verbose_name='Sexe')),
                ('height_cm', models.PositiveIntegerField(help_text='Exemple : 178 pour 1m78', verbose_name='Taille (en cm)')),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Poids (en kg)')),
                ('measurements', models.CharField(blank=True, help_text='Poitrine - Taille - Hanches (ex: 88-62-92)', max_length=100, verbose_name='Mensurations')),
                ('city', models.CharField(max_length=120, verbose_name='Ville')),
                ('country', models.CharField(default='Cameroun', max_length=120, verbose_name='Pays de résidence')),
                ('is_international', models.BooleanField(default=False, verbose_name='Candidature internationale')),
                ('phone', models.CharField(db_index=True, max_length=35, verbose_name='Numéro WhatsApp / Téléphone')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Adresse email')),
                ('experience', models.TextField(blank=True, verbose_name='Expérience / Défilés précédents')),
                ('social_links', models.CharField(blank=True, max_length=255, verbose_name='Réseaux sociaux (Instagram, TikTok)')),
                ('candidate_number', models.CharField(db_index=True, help_text='Format auto : CAST-2026-0001', max_length=35, unique=True, verbose_name='Numéro de candidature')),
                ('access_code', models.CharField(db_index=True, help_text='Code unique permettant au candidat de se connecter et suivre sa candidature', max_length=25, unique=True, verbose_name="Code d'accès candidat")),
                ('status', models.CharField(choices=[('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('EN_ATTENTE_VALIDATION', 'Preuve soumise / En attente de validation'), ('INSCRIT', 'Inscrit (Paiement validé)'), ('PRESELECTIONNE', 'Présélectionné'), ('RETENU', 'Retenu'), ('REFUSE', 'Refusé')], db_index=True, default='EN_ATTENTE_PAIEMENT', max_length=35, verbose_name='Statut du candidat')),
                ('video_url', models.URLField(blank=True, help_text='Vidéo 30 à 60s (Lien YouTube, TikTok, Drive, Instagram...)', verbose_name='Lien vidéo de présentation')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='artist_hub/casting/videos/%Y/%m/', verbose_name='Fichier vidéo téléversé (30-60s)')),
                ('is_minor', models.BooleanField(default=False, verbose_name='Est mineur (< 18 ans)')),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='Nom complet du tuteur légal')),
                ('guardian_phone', models.CharField(blank=True, max_length=35, verbose_name='Téléphone du tuteur légal')),
                ('parental_consent', models.BooleanField(default=False, verbose_name='Autorisation parentale accordée')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Consentement traitement données personnelles')),
                ('selection_disclaimer_accepted', models.BooleanField(default=False, verbose_name='Accord clause : les frais ne garantissent pas la sélection')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes internes du jury / staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de candidature')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CastingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Douala Fashion Week 2026', max_length=200, verbose_name='Titre du casting')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug URL')),
                ('subtitle', models.CharField(blank=True, default='Samedi 26 Décembre 2026 — Hôtel Krystal Palace Douala', max_length=255, verbose_name='Sous-titre / Date & Lieu')),
                ('description', models.TextField(blank=True, help_text="Présentation de l'événement et du profil recherché", verbose_name='Description')),
                ('rules', models.TextField(blank=True, default="1. Le paiement des frais de casting est obligatoire pour valider la candidature.\n2. IMPORTANT : Le paiement des frais de casting ne garantit en aucun cas la sélection finale.\n3. Les candidats mineurs doivent impérativement fournir l'autorisation d'un tuteur légal.\n4. Les photos et vidéos fournies doivent être récentes, fidèles et sans filtres déformants.", verbose_name='Règlement & conditions')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('event_location', models.CharField(default='Hôtel Krystal Palace, Douala', max_length=255, verbose_name="Lieu de l'événement")),
                ('fee_cameroon', models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='Frais Candidats Cameroun (FCFA)')),
                ('fee_international', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Frais Candidats International (FCFA)')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='Devise')),
                ('min_height_male', models.PositiveIntegerField(default=183, help_text='Affiche officielle : 1m83 minimum', verbose_name='Taille minimum Hommes (cm)')),
                ('min_height_female', models.PositiveIntegerField(default=175, help_text='Affiche officielle : 1m75 minimum', verbose_name='Taille minimum Femmes (cm)')),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ouverture des inscriptions")),
                ('closes_at', models.DateTimeField(blank=True, help_text='Date limite : ex. 28 septembre 2026 à 23h59', null=True, verbose_name='Date de clôture des inscriptions')),
                ('max_candidates', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre maximum de candidatures (optionnel)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artist_hub/casting/covers/', verbose_name='Affiche / Image de couverture')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Session active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session de Casting',
                'verbose_name_plural': 'Sessions de Casting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pass')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='Quantité totale')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de billet',
                'verbose_name_plural': 'Catégories de billets',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=35)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('DECLINED', 'Refusée'), ('PAID', 'Acompte réglé')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='artist_hub.bookingservice')),
            ],
            options={
                'verbose_name': 'Demande de réservation',
                'verbose_name_plural': 'Demandes de réservation',
            },
        ),
        migrations.CreateModel(
            name='CandidatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('portrait', 'Photo 1 — Portrait / Visage'), ('full_length', 'Photo 2 — Plein pied'), ('profile', 'Photo profil'), ('other', 'Autre photo')], default='portrait', max_length=25, verbose_name='Type de photo')),
                ('image', models.ImageField(upload_to='artist_hub/casting/photos/%Y/%m/', verbose_name='Image')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='artist_hub.candidate', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Photo de candidat',
                'verbose_name_plural': 'Photos de candidat',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='artist_hub.castingsession', verbose_name='Session de casting'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Exemple : PAY-20261002-XYZ', max_length=64, unique=True, verbose_name='Référence unique')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='Devise')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], db_index=True, default='PENDING', max_length=30, verbose_name='Statut')),
                ('provider', models.CharField(default='mock', help_text='manual_proof, mock, notchpay, cinetpay', max_length=50, verbose_name='Fournisseur de paiement')),
                ('method', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('ecobank_rib', 'Virement / Dépôt Ecobank'), ('card', 'Carte bancaire (Visa / Mastercard)'), ('manual', 'Manuel / Espèces / Autre')], default='mtn_momo', max_length=50, verbose_name='Méthode de paiement')),
                ('payer_name', models.CharField(blank=True, max_length=150, verbose_name='Nom du payeur')),
                ('payer_phone', models.CharField(blank=True, max_length=35, verbose_name='Téléphone du payeur')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du payeur')),
                ('external_reference', models.CharField(blank=True, help_text='ID de transaction renvoyé par MoMo/OM/passerelle', max_length=150, verbose_name='Référence externe opérateur / passerelle')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='artist_hub/proofs/%Y/%m/', verbose_name='Preuve de paiement (capture/reçu)')),
                ('proof_notes', models.TextField(blank=True, verbose_name='Notes ou détails du versement')),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Données brutes reçues (webhook/API)')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_payments', to='contenttypes.contenttype')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_hub_verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (staff)')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='artist_hub.payment', verbose_name='Paiement associé'),
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=35)),
                ('qr_code_token', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='artist_hub.eventticketcategory')),
            ],
            options={
                'verbose_name': 'Billet acheté',
                'verbose_name_plural': 'Billets achetés',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference', 'status'], name='artist_hub__referen_19b4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['content_type', 'object_id'], name='artist_hub__content_1ffc73_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_phone'], name='artist_hub__payer_p_e67d37_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', 'session'], name='artist_hub__status_353c06_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['candidate_number'], name='artist_hub__candida_4ad313_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['access_code'], name='artist_hub__access__d93b48_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('session', 'phone'), name='unique_candidate_phone_per_session'),
        ),
    ]
