# Generated by Django 6.0.2 on 2026-10-02 09:08

import artist_hub.payments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, storage=artist_hub.payments.storage.private_proof_storage, upload_to='artist_hub/proofs/%Y/%m/', verbose_name='Preuve de paiement (capture/reçu)'),
        ),
    ]
