# Generated by Django 6.0.2 on 2026-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_hub', '0002_alter_payment_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE_PAIEMENT', 'À confirmer'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('INSCRIT', 'Inscription confirmée'), ('PRESELECTIONNE', 'Présélectionné'), ('RETENU', 'Retenu'), ('REFUSE', 'Refusé')], db_index=True, default='EN_ATTENTE_PAIEMENT', max_length=35, verbose_name='Statut du candidat'),
        ),
        migrations.AlterField(
            model_name='castingsession',
            name='fee_cameroon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais Candidats Cameroun (FCFA)'),
        ),
        migrations.AlterField(
            model_name='castingsession',
            name='fee_international',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais Candidats International (FCFA)'),
        ),
        migrations.AlterField(
            model_name='castingsession',
            name='rules',
            field=models.TextField(blank=True, default="1. Le casting est gratuit.\n2. L’inscription ne garantit pas la sélection finale.\n3. Les candidats mineurs doivent impérativement fournir l'autorisation d'un tuteur légal.\n4. Les photos et vidéos fournies doivent être récentes, fidèles et sans filtres déformants.", verbose_name='Règlement & conditions'),
        ),
    ]
