# Generated by Django 6.0.2 on 2026-10-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_hub', '0004_free_casting'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingsession',
            name='casting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du casting'),
        ),
    ]
