# Generated by Django 5.0.6 on 2026-06-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='generated/videos/')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='running', max_length=30)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='stories.storyproject')),
            ],
        ),
    ]
