# Generated by Django 5.0.6 on 2026-06-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storyproject_avatar_background_and_more'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(default='avatar', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=30)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='stories.storyproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
