# Generated by Django 6.0.2 on 2026-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishPrepApp', '0007_englisheesubmission_englisheosubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishquestion',
            name='skill',
            field=models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('USE_OF_ENGLISH', 'Grammar / Vocabulary')], default='READING', max_length=20),
        ),
    ]
