# Generated by Django 6.0.2 on 2026-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrule',
            name='section',
            field=models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services'), ('gaz', 'Gaz domestique'), ('pressing', 'Pressing'), ('sante', 'Santé / Pharmacies'), ('jobs', 'Jobs / Emplois'), ('business', 'Prestataires E-Shelle'), ('chat_ai', 'Chat IA E-Shelle')], max_length=50, unique=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='posttemplate',
            name='section',
            field=models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services'), ('gaz', 'Gaz domestique'), ('pressing', 'Pressing'), ('sante', 'Santé / Pharmacies'), ('jobs', 'Jobs / Emplois'), ('business', 'Prestataires E-Shelle'), ('chat_ai', 'Chat IA E-Shelle')], max_length=50, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='publishedpost',
            name='section',
            field=models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services'), ('gaz', 'Gaz domestique'), ('pressing', 'Pressing'), ('sante', 'Santé / Pharmacies'), ('jobs', 'Jobs / Emplois'), ('business', 'Prestataires E-Shelle'), ('chat_ai', 'Chat IA E-Shelle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='section',
            field=models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services'), ('gaz', 'Gaz domestique'), ('pressing', 'Pressing'), ('sante', 'Santé / Pharmacies'), ('jobs', 'Jobs / Emplois'), ('business', 'Prestataires E-Shelle'), ('chat_ai', 'Chat IA E-Shelle')], max_length=50, verbose_name='Section'),
        ),
    ]
