# Generated by Django 6.0.2 on 2026-06-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rencontres', '0004_photo_validation_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpremiumrencontre',
            name='nom',
            field=models.CharField(choices=[('silver', '3 jours'), ('gold', '10 jours'), ('platinum', '1 mois')], max_length=20, unique=True),
        ),
    ]
