# Generated by Django 6.0.2 on 2026-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rencontres', '0005_alter_planpremiumrencontre_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilrencontre',
            name='boost_fin',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profilrencontre',
            name='boost_utilisations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profilrencontre',
            name='incognito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abonnementrencontre',
            name='renouvellement_auto',
            field=models.BooleanField(default=False),
        ),
    ]
