# Generated by Django 6.0.2 on 2026-05-28 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetierArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icone', models.CharField(default='tools', max_length=40)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Métier artisan',
                'verbose_name_plural': 'Métiers artisans',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='VilleArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=90)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('region', models.CharField(blank=True, max_length=90)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ville artisans',
                'verbose_name_plural': 'Villes artisans',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_public', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('quartier', models.CharField(blank=True, max_length=120)),
                ('zone_intervention', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('telephone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artisans/profils/')),
                ('compte_type', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('PREMIUM', 'Premium'), ('BUSINESS', 'Business')], default='GRATUIT', max_length=20)),
                ('date_expiration_premium', models.DateField(blank=True, null=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('disponible_urgence', models.BooleanField(default=False)),
                ('intervention_domicile', models.BooleanField(default=True)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('contacts', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metiers', models.ManyToManyField(related_name='artisans', to='artisans.metierartisan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_artisan', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artisans', to='artisans.villeartisan')),
            ],
            options={
                'verbose_name': 'Profil artisan',
                'verbose_name_plural': 'Profils artisans',
                'ordering': ['-compte_type', '-est_verifie', '-note_moyenne', 'nom_public'],
            },
        ),
        migrations.CreateModel(
            name='RealisationArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160)),
                ('image', models.ImageField(upload_to='artisans/realisations/')),
                ('description', models.CharField(blank=True, max_length=220)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='artisans.profilartisan')),
            ],
            options={
                'verbose_name': 'Réalisation artisan',
                'verbose_name_plural': 'Réalisations artisans',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemandeTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=30)),
                ('quartier', models.CharField(blank=True, max_length=120)),
                ('besoin', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='artisans.metierartisan')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='artisans.villeartisan')),
            ],
            options={
                'verbose_name': 'Demande de travaux',
                'verbose_name_plural': 'Demandes de travaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
