# Generated by Django 5.2.7 on 2025-11-11 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField()),
                ('delai_traitement', models.CharField(max_length=100)),
                ('cout_visa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_acceptation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='CountryGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='visaetude.country')),
            ],
            options={
                'verbose_name': 'Guide Pays',
                'verbose_name_plural': 'Guides Pays',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('reponse', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('populaire', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='visaetude.country')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-populaire', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_prevue', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('date_completion', models.DateField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaetude.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jalons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jalon',
                'verbose_name_plural': 'Jalons',
                'ordering': ['ordre', 'date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exemple', models.FileField(blank=True, null=True, upload_to='documents/exemples/')),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_requis', to='visaetude.country')),
            ],
            options={
                'verbose_name': 'Document Requis',
                'verbose_name_plural': 'Documents Requis',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_origine', models.CharField(choices=[('cameroun', 'Cameroun'), ('senegal', 'Sénégal'), ('cote_ivoire', "Côte d'Ivoire"), ('autre', 'Autre')], max_length=50)),
                ('niveau_etude', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat')], max_length=20)),
                ('domaine_etude', models.CharField(max_length=100)),
                ('budget_disponible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('complete', 'Complété')], default='non_commence', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/users/')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaetude.requireddocument')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaetude.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Utilisateur',
                'verbose_name_plural': 'Checklists Utilisateurs',
                'unique_together': {('user', 'document')},
            },
        ),
    ]
