# Generated by Django 5.2.7 on 2025-11-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaetude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifiant du pays, ex: canada, france, belgique', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pays')),
                ('short_label', models.CharField(blank=True, help_text='Ex: Destination francophone abordable pour les masters', max_length=150, verbose_name='Label court (optionnel)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pays – Visa Études',
                'verbose_name_plural': 'Pays – Visa Études',
            },
        ),
        migrations.CreateModel(
            name='VisaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la ressource')),
                ('step_label', models.CharField(blank=True, help_text='Ex: "Remplir le formulaire de visa en ligne"', max_length=120, verbose_name='Étape / description courte')),
                ('category', models.CharField(choices=[('admission', 'Admission / Universités'), ('visa', 'Visa étudiant'), ('bourse', 'Bourses d’étude'), ('rdv', 'Prise de rendez-vous'), ('divers', 'Autres (guides, astuces)')], max_length=20, verbose_name='Catégorie')),
                ('resource_type', models.CharField(choices=[('video', 'Vidéo'), ('capture', 'Captures d’écran'), ('pdf', 'PDF / Guide')], default='video', max_length=20, verbose_name='Type de ressource')),
                ('url', models.URLField(help_text='Lien vers la vidéo / page tutoriel / dossier Drive', verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre d’affichage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='visaetude.visacountry')),
            ],
            options={
                'verbose_name': 'Ressource (vidéo / guide) – Visa Études',
                'verbose_name_plural': 'Ressources (vidéos / guides) – Visa Études',
                'ordering': ['country', 'order', 'title'],
            },
        ),
    ]
