# Generated by Django 5.2.7 on 2025-11-20 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaetude', '0002_visacountry_visaresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visaetude_jalons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchecklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visaetude_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visaetude_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1_profile', models.BooleanField(default=False)),
                ('step_2_country', models.BooleanField(default=False)),
                ('step_3_checklist', models.BooleanField(default=False)),
                ('step_4_documents', models.BooleanField(default=False)),
                ('step_5_coach', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Visa Études',
                'verbose_name_plural': 'Progressions Visa Études',
            },
        ),
    ]
