# Generated by Django 5.2.7 on 2025-11-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaetude', '0003_alter_milestone_user_alter_userchecklist_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_title', models.CharField(max_length=255)),
                ('advice_content', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='visaetude.visacountry')),
            ],
            options={
                'verbose_name': 'Conseil',
                'verbose_name_plural': 'Conseils',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('application_link', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='visaetude.visacountry')),
            ],
            options={
                'verbose_name': 'Bourse',
                'verbose_name_plural': 'Bourses',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admission_link', models.URLField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='visaetude.visacountry')),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
            },
        ),
    ]
