# Generated by Django 5.2.7 on 2025-12-30 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaetude', '0004_countryadvice_scholarship_university'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='requireddocument',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='countryadvice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userchecklist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visacountry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visaresource',
            options={'ordering': ['country', 'order']},
        ),
        migrations.RenameField(
            model_name='userchecklist',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userchecklist',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='userchecklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userchecklist',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='visaetude.visacountry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchecklist',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchecklist',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='visaetude/documents/'),
        ),
        migrations.AlterField(
            model_name='visacountry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visacountry',
            name='short_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='visacountry',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='visaresource',
            name='category',
            field=models.CharField(choices=[('admission', 'Admission'), ('visa', 'Visa étudiant'), ('bourse', 'Bourses'), ('rdv', 'Rendez-vous'), ('divers', 'Divers')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visaresource',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visaresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'PDF'), ('capture', 'Capture')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='visaresource',
            name='step_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='visaresource',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visaresource',
            name='url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='VisaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1_profile', models.BooleanField(default=False)),
                ('step_2_country', models.BooleanField(default=False)),
                ('step_3_checklist', models.BooleanField(default=False)),
                ('step_4_documents', models.BooleanField(default=False)),
                ('step_5_coach', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CountryGuide',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.RemoveField(
            model_name='userchecklist',
            name='document',
        ),
        migrations.RemoveField(
            model_name='userchecklist',
            name='pays',
        ),
        migrations.DeleteModel(
            name='RequiredDocument',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
