# Generated by Django 5.2.7 on 2026-01-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visaetude', '0006_userprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='current_step',
            new_name='step_2_country',
        ),
    ]
