# Generated by Django 5.2.7 on 2026-01-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaetude', '0007_rename_current_step_userprogress_step_2_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='step_1_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='step_5_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='step_2_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('field_of_study', models.CharField(max_length=200)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('target_year', models.IntegerField()),
                ('education_level', models.CharField(max_length=100)),
                ('language_level', models.CharField(max_length=100)),
                ('study_goal', models.TextField()),
                ('budget_range', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
