# Generated by Django 6.0.2 on 2026-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0029_alter_userskillprogress_current_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('co', 'Compréhension Orale'), ('ce', 'Compréhension Écrite'), ('ee', 'Expression Écrite'), ('eo', 'Expression Orale')], max_length=2)),
                ('label', models.CharField(help_text='ex: « accord du participe passé », « intonation interrogative »', max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tag de compétence',
                'ordering': ['skill', 'label'],
            },
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='competency_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags de compétences testées par cet exercice', related_name='exercises', to='preparation_tests.competencytag'),
        ),
    ]
