# Generated by Django 6.0.2 on 2026-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0030_competencytag_courseexercise_competency_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexercise',
            name='document_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='document_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
