# Generated by Django 5.2.7 on 2026-01-17 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='fr', max_length=8)),
                ('source', models.CharField(default='wizard', max_length=32)),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eligibility Session',
                'verbose_name_plural': 'Eligibility Sessions',
                'ordering': ['-id'],
            },
        ),
    ]
