# Generated by Django 5.2.7 on 2025-11-08 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('study', 'study'), ('work', 'work'), ('pr', 'pr')], max_length=16)),
                ('url_official', models.URLField()),
                ('min_score', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('eta_days', models.PositiveIntegerField(default=7)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='eligibility.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('doc_code', models.CharField(max_length=64)),
                ('is_required', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='eligibility.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('op', models.CharField(choices=[('gte', 'gte'), ('lte', 'lte'), ('eq', 'eq'), ('in', 'in'), ('bool', 'bool')], max_length=8)),
                ('value_json', models.JSONField()),
                ('weight', models.FloatField(default=1.0)),
                ('required', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='eligibility.program')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='fr', max_length=8)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('score_total', models.FloatField(blank=True, null=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value_json', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='eligibility.session')),
            ],
        ),
    ]
