# Generated by Django 5.0.6 on 2026-06-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220)),
                ('prompt', models.TextField()),
                ('story_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('running', 'Génération en cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='draft', max_length=30)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('final_video', models.FileField(blank=True, null=True, upload_to='generated/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
