# Generated by Django 5.0.6 on 2026-06-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyproject',
            name='avatar_background',
            field=models.CharField(blank=True, default='office', max_length=100),
        ),
        migrations.AddField(
            model_name='storyproject',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='storyproject',
            name='is_avatar_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyproject',
            name='script_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storyproject',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
