# Generated by Django 5.0.6 on 2026-06-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storyproject_avatar_background_and_more'),
        ('voices', '0002_clonedvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyproject',
            name='cloned_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='voices.clonedvoice'),
        ),
    ]
