# Generated by Django 6.0.2 on 2026-05-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchaslucpay_notifications', '0003_alter_notificationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], db_index=True, max_length=10),
        ),
    ]
