# Generated by Django 5.2.7 on 2026-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('category', models.CharField(choices=[('guides_pdf', 'Guides PDF'), ('tableaux_excel', 'Tableaux Excel'), ('preparation_tcf', 'Préparation TCF'), ('visa_immigration', 'Visa & Immigration'), ('emploi_international', 'Emploi International')], max_length=50, verbose_name='Catégorie')),
                ('destination', models.CharField(choices=[('canada', 'Canada'), ('italie', 'Italie'), ('uk', 'UK'), ('japon', 'Japon'), ('espagne', 'Espagne'), ('europe', 'Europe'), ('international', 'International'), ('france', 'France'), ('belgique', 'Belgique'), ('maroc', 'Maroc')], default='international', max_length=50, verbose_name='Destination')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('xls', 'Excel'), ('doc', 'Word'), ('other', 'Autre')], default='pdf', max_length=10, verbose_name='Type de fichier')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Fichier')),
                ('file_size', models.CharField(blank=True, help_text='Ex : 2.4 Mo — rempli auto si vide', max_length=20, verbose_name='Taille affichée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Réservé Premium')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
