# Generated by Django 5.0.6 on 2026-06-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('final_video', models.FileField(blank=True, null=True, upload_to='generated/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_projects', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(default='1080x1920', max_length=20)),
                ('aspect', models.CharField(default='vertical', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to='ads.adproject')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default='coqui', max_length=80)),
                ('audio', models.FileField(blank=True, null=True, upload_to='generated/audio/')),
                ('language', models.CharField(default='fr', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_tracks', to='ads.adproject')),
            ],
        ),
    ]
