# Generated by Django 5.2.7 on 2025-10-21 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profession', models.CharField(blank=True, max_length=128)),
                ('country_target', models.CharField(blank=True, max_length=64)),
                ('template_id', models.CharField(blank=True, max_length=64)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('experiences', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
