# Generated by Django 5.2.7 on 2025-10-23 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0002_cvtemplate_remove_cv_ai_feedback_remove_cv_ai_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Taille en bytes', null=True)),
            ],
            options={
                'verbose_name': "Historique d'export",
                'verbose_name_plural': 'Historique des exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-date_modification'], 'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
        migrations.AlterModelOptions(
            name='cvtemplate',
            options={'ordering': ['-popularity_score', '-created_at'], 'verbose_name': 'Modèle de CV', 'verbose_name_plural': 'Modèles de CV'},
        ),
        migrations.AddField(
            model_name='cv',
            name='current_step',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Étape actuelle'),
        ),
        migrations.AddField(
            model_name='cv',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation'),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='CV publié'),
        ),
        migrations.AddField(
            model_name='cv',
            name='last_analysis',
            field=models.JSONField(blank=True, help_text="Résultats de l'analyse de qualité du CV", null=True, verbose_name='Dernière analyse IA'),
        ),
        migrations.AddField(
            model_name='cv',
            name='quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de qualité'),
        ),
        migrations.AddField(
            model_name='cv',
            name='step1_completed',
            field=models.BooleanField(default=False, verbose_name='Étape 1 complétée'),
        ),
        migrations.AddField(
            model_name='cv',
            name='step2_completed',
            field=models.BooleanField(default=False, verbose_name='Étape 2 complétée'),
        ),
        migrations.AddField(
            model_name='cv',
            name='step3_completed',
            field=models.BooleanField(default=False, verbose_name='Étape 3 complétée'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='style_type',
            field=models.CharField(choices=[('professional', 'Professionnel'), ('creative', 'Créatif'), ('traditional', 'Traditionnel'), ('modern', 'Moderne'), ('canadian', 'Canadien'), ('european', 'Européen'), ('american', 'Américain')], default='professional', max_length=50, verbose_name='Type de style'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Structure: {personal_info, experiences, education, skills, languages, summary, etc.}', verbose_name='Données du CV'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession/Titre du poste'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='html_template',
            field=models.TextField(verbose_name='Template HTML'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='industry',
            field=models.CharField(max_length=100, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du modèle'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='popularity_score',
            field=models.IntegerField(default=0, verbose_name='Score de popularité'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cv_templates/', verbose_name='Aperçu'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['utilisateur', '-date_modification'], name='cv_generato_utilisa_50a20c_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['is_completed', 'is_published'], name='cv_generato_is_comp_c2d13f_idx'),
        ),
        migrations.AddField(
            model_name='cvexporthistory',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cv_generator.cv'),
        ),
    ]
