# Generated by Django 5.2.7 on 2025-11-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0004_education_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='description_optimised',
            field=models.TextField(blank=True, verbose_name='Description optimisée IA'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_raw',
            field=models.TextField(default=1, verbose_name='Description brute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Dernière analyse IA'),
        ),
    ]
