# Generated by Django 5.2.7 on 2025-11-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0005_remove_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AddField(
            model_name='cv',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Résumé professionnel'),
        ),
        migrations.AlterField(
            model_name='cvexporthistory',
            name='export_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name="Format d'export"),
        ),
        migrations.AlterField(
            model_name='cvexporthistory',
            name='exported_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'export"),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='diploma',
            field=models.CharField(max_length=150, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=150, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la certification')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisme')),
                ('date_obtained', models.DateField(verbose_name="Date d'obtention")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID de certification')),
                ('credential_url', models.URLField(blank=True, verbose_name='URL de vérification')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du loisir')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': "Centre d'intérêt",
                'verbose_name_plural': "Centres d'intérêt",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Langue')),
                ('level', models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Intermédiaire avancé'), ('C1', 'C1 - Avancé'), ('C2', 'C2 - Maîtrise'), ('natif', 'Langue maternelle')], max_length=20, verbose_name='Niveau')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('url', models.URLField(blank=True, verbose_name='URL du projet')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Technologies utilisées')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('category', models.CharField(choices=[('technique', 'Compétence Technique'), ('soft', 'Soft Skill'), ('langue', 'Langue'), ('outil', 'Outil/Logiciel')], default='technique', max_length=50, verbose_name='Catégorie')),
                ('level', models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=50, verbose_name='Niveau')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation')),
                ('role', models.CharField(max_length=200, verbose_name='Rôle')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='cv_generator.cv')),
            ],
            options={
                'verbose_name': 'Expérience bénévole',
                'verbose_name_plural': 'Expériences bénévoles',
                'ordering': ['-start_date'],
            },
        ),
    ]
